// 离线词库分片 1/5（由 split_offline_dict.js 生成，勿手改）
var OFFLINE_EXTRA_1 = [
{"word":"ability","ipa":"/əˈbɪləti/","pos":"n.","cat":"cet4","meaning":"能力；才能","example":"She has the ability to solve hard problems.","exampleZh":"她有解决难题的能力。"},
{"word":"aboard","ipa":"/əˈbɔːrd/","pos":"adv./prep.","cat":"cet4","meaning":"在船/车/飞机上；上船/车/飞机","example":"Welcome aboard the train.","exampleZh":"欢迎登上这趟列车。"},
{"word":"absence","ipa":"/ˈæbsəns/","pos":"n.","cat":"cet4","meaning":"缺席；缺乏","example":"His absence from the meeting was noticed.","exampleZh":"他缺席会议被人注意到了。"},
{"word":"absolute","ipa":"/ˈæbsəluːt/","pos":"adj.","cat":"cet4","meaning":"绝对的；完全的","example":"There is no absolute truth.","exampleZh":"没有绝对真理。"},
{"word":"academic","ipa":"/ˌækəˈdemɪk/","pos":"adj.","cat":"cet4","meaning":"学术的；学校的","example":"Academic performance matters for admission.","exampleZh":"学业表现对录取很重要。"},
{"word":"accept","ipa":"/əkˈsept/","pos":"v.","cat":"cet4","meaning":"接受；同意","example":"I accept your invitation.","exampleZh":"我接受你的邀请。"},
{"word":"access","ipa":"/ˈækses/","pos":"n./v.","cat":"cet4","meaning":"通道；接近；获取","example":"Students need access to the library.","exampleZh":"学生需要能使用图书馆。"},
{"word":"accident","ipa":"/ˈæksɪdənt/","pos":"n.","cat":"cet4","meaning":"意外；事故","example":"A traffic accident blocked the road.","exampleZh":"一起交通事故封锁了道路。"},
{"word":"accompany","ipa":"/əˈkʌmpəni/","pos":"v.","cat":"cet4","meaning":"陪伴；伴随","example":"She accompanied her friend to the hospital.","exampleZh":"她陪朋友去了医院。"},
{"word":"accomplish","ipa":"/əˈkʌmplɪʃ/","pos":"v.","cat":"cet4","meaning":"完成；实现","example":"We accomplished the task on time.","exampleZh":"我们按时完成了任务。"},
{"word":"according","ipa":"/əˈkɔːrdɪŋ/","pos":"adv.","cat":"cet4","meaning":"按照；根据","example":"According to the plan, we start today.","exampleZh":"根据计划，我们今天开始。"},
{"word":"account","ipa":"/əˈkaʊnt/","pos":"n./v.","cat":"cet4","meaning":"账户；解释；占","example":"Please account for the missing money.","exampleZh":"请解释这笔钱为何短缺。"},
{"word":"accurate","ipa":"/ˈækjərət/","pos":"adj.","cat":"cet4","meaning":"准确的；精确的","example":"The data must be accurate.","exampleZh":"数据必须准确。"},
{"word":"achieve","ipa":"/əˈtʃiːv/","pos":"v.","cat":"cet4","meaning":"达成；实现","example":"He achieved his dream at last.","exampleZh":"他终于实现了梦想。"},
{"word":"acquire","ipa":"/əˈkwaɪər/","pos":"v.","cat":"cet4","meaning":"获得；习得","example":"Children acquire language quickly.","exampleZh":"儿童学语言很快。"},
{"word":"active","ipa":"/ˈæktɪv/","pos":"adj.","cat":"cet4","meaning":"活跃的；积极的","example":"She leads an active lifestyle.","exampleZh":"她生活很积极。"},
{"word":"actual","ipa":"/ˈæktʃuəl/","pos":"adj.","cat":"cet4","meaning":"实际的；真实的","example":"The actual cost was higher.","exampleZh":"实际花费更高。"},
{"word":"adapt","ipa":"/əˈdæpt/","pos":"v.","cat":"cet4","meaning":"适应；改编","example":"We adapted to the new rules.","exampleZh":"我们适应了新规则。"},
{"word":"adequate","ipa":"/ˈædɪkwət/","pos":"adj.","cat":"cet4","meaning":"足够的；恰当的","example":"The supply is not adequate.","exampleZh":"供应不够充足。"},
{"word":"adjust","ipa":"/əˈdʒʌst/","pos":"v.","cat":"cet4","meaning":"调整；使适应","example":"Adjust the seat before driving.","exampleZh":"开车前调一下座椅。"},
{"word":"administration","ipa":"/ədˌmɪnɪˈstreɪʃn/","pos":"n.","cat":"cet4","meaning":"管理；行政部门","example":"The administration approved the budget.","exampleZh":"行政部门批准了预算。"},
{"word":"admire","ipa":"/ədˈmaɪər/","pos":"v.","cat":"cet4","meaning":"钦佩；欣赏","example":"I admire her courage.","exampleZh":"我钦佩她的勇气。"},
{"word":"admit","ipa":"/ədˈmɪt/","pos":"v.","cat":"cet4","meaning":"承认；准许进入","example":"He admitted his mistake.","exampleZh":"他承认了错误。"},
{"word":"adopt","ipa":"/əˈdɒpt/","pos":"v.","cat":"cet4","meaning":"采纳；收养","example":"They adopted a new policy.","exampleZh":"他们采纳了新政策。"},
{"word":"advance","ipa":"/ədˈvæns/","pos":"v./n.","cat":"cet4","meaning":"推进；进步","example":"Technology advances rapidly.","exampleZh":"技术飞速进步。"},
{"word":"advantage","ipa":"/ədˈvæntɪdʒ/","pos":"n.","cat":"cet4","meaning":"优势；好处","example":"The location is a big advantage.","exampleZh":"这个位置是个大优势。"},
{"word":"adventure","ipa":"/ədˈventʃər/","pos":"n.","cat":"cet4","meaning":"冒险；奇遇","example":"The trip was a real adventure.","exampleZh":"这趟旅行真是一场冒险。"},
{"word":"advise","ipa":"/ədˈvaɪz/","pos":"v.","cat":"cet4","meaning":"建议","example":"I advise you to rest.","exampleZh":"我建议你休息。"},
{"word":"affair","ipa":"/əˈfer/","pos":"n.","cat":"cet4","meaning":"事务；事件","example":"This is a private affair.","exampleZh":"这是私事。"},
{"word":"affect","ipa":"/əˈfekt/","pos":"v.","cat":"cet4","meaning":"影响","example":"The weather affects our mood.","exampleZh":"天气影响心情。"},
{"word":"afford","ipa":"/əˈfɔːrd/","pos":"v.","cat":"cet4","meaning":"负担得起","example":"We cannot afford the price.","exampleZh":"我们付不起这个价。"},
{"word":"afraid","ipa":"/əˈfreɪd/","pos":"adj.","cat":"cet4","meaning":"害怕的；担心的","example":"She is afraid of dogs.","exampleZh":"她怕狗。"},
{"word":"agency","ipa":"/ˈeɪdʒənsi/","pos":"n.","cat":"cet4","meaning":"机构；代理","example":"He works for a travel agency.","exampleZh":"他在旅行社工作。"},
{"word":"agenda","ipa":"/əˈdʒendə/","pos":"n.","cat":"cet4","meaning":"议程；待办事项","example":"The first item on the agenda is safety.","exampleZh":"议程第一项是安全。"},
{"word":"agent","ipa":"/ˈeɪdʒənt/","pos":"n.","cat":"cet4","meaning":"代理人；特工","example":"A real-estate agent showed us the flat.","exampleZh":"房产中介带我们看房。"},
{"word":"aggressive","ipa":"/əˈɡresɪv/","pos":"adj.","cat":"cet4","meaning":"好斗的；积极进取的","example":"The firm took an aggressive strategy.","exampleZh":"公司采取了激进策略。"},
{"word":"aid","ipa":"/eɪd/","pos":"n./v.","cat":"cet4","meaning":"帮助；援助","example":"They aided the victims.","exampleZh":"他们援助了受害者。"},
{"word":"alarm","ipa":"/əˈlɑːrm/","pos":"n./v.","cat":"cet4","meaning":"警报；使惊恐","example":"The fire alarm went off.","exampleZh":"火警响了。"},
{"word":"alcohol","ipa":"/ˈælkəhɔːl/","pos":"n.","cat":"cet4","meaning":"酒精；酒","example":"He does not drink alcohol.","exampleZh":"他不喝酒。"},
{"word":"allow","ipa":"/əˈlaʊ/","pos":"v.","cat":"cet4","meaning":"允许","example":"Pets are not allowed here.","exampleZh":"这里不允许养宠物。"},
{"word":"alone","ipa":"/əˈloʊn/","pos":"adj./adv.","cat":"cet4","meaning":"单独的（地）","example":"She lives alone in the city.","exampleZh":"她独自住在城里。"},
{"word":"alter","ipa":"/ˈɔːltər/","pos":"v.","cat":"cet4","meaning":"改变；修改","example":"We altered the schedule.","exampleZh":"我们改了日程。"},
{"word":"alternative","ipa":"/ɔːlˈtɜːrnətɪv/","pos":"n./adj.","cat":"cet4","meaning":"替代方案；备选的","example":"Is there an alternative route?","exampleZh":"有别的路线吗？"},
{"word":"amaze","ipa":"/əˈmeɪz/","pos":"v.","cat":"cet4","meaning":"使惊奇","example":"Her talent amazed the judges.","exampleZh":"她的才华令评委惊叹。"},
{"word":"ambition","ipa":"/æmˈbɪʃn/","pos":"n.","cat":"cet4","meaning":"野心；抱负","example":"His ambition is to be a doctor.","exampleZh":"他的志向是当医生。"},
{"word":"amount","ipa":"/əˈmaʊnt/","pos":"n./v.","cat":"cet4","meaning":"数量；合计","example":"A large amount of water was wasted.","exampleZh":"大量水被浪费了。"},
{"word":"analysis","ipa":"/əˈnæləsɪs/","pos":"n.","cat":"cet4","meaning":"分析","example":"The analysis showed a clear trend.","exampleZh":"分析显示出一个明确趋势。"},
{"word":"analyze","ipa":"/ˈænəlaɪz/","pos":"v.","cat":"cet4","meaning":"分析","example":"We analyzed the survey results.","exampleZh":"我们分析了调查结果。"},
{"word":"ancient","ipa":"/ˈeɪnʃənt/","pos":"adj.","cat":"cet4","meaning":"古代的；古老的","example":"They visited an ancient temple.","exampleZh":"他们参观了一座古庙。"},
{"word":"anger","ipa":"/ˈæŋɡər/","pos":"n./v.","cat":"cet4","meaning":"愤怒；使发怒","example":"His words sparked anger.","exampleZh":"他的话引发了愤怒。"},
{"word":"angle","ipa":"/ˈæŋɡl/","pos":"n.","cat":"cet4","meaning":"角度","example":"Look at the problem from a new angle.","exampleZh":"换个角度看这个问题。"},
{"word":"annoy","ipa":"/əˈnɔɪ/","pos":"v.","cat":"cet4","meaning":"使烦恼；打扰","example":"The noise annoyed the neighbors.","exampleZh":"噪音吵到了邻居。"},
{"word":"annual","ipa":"/ˈænjuəl/","pos":"adj.","cat":"cet4","meaning":"每年的","example":"The annual meeting is in December.","exampleZh":"年会定在十二月。"},
{"word":"anticipate","ipa":"/ænˈtɪsɪpeɪt/","pos":"v.","cat":"cet4","meaning":"预期； anticipation","example":"We anticipate a busy season.","exampleZh":"我们预计会迎来旺季。"},
{"word":"anxiety","ipa":"/æŋˈzaɪəti/","pos":"n.","cat":"cet4","meaning":"焦虑；忧虑","example":"Exam anxiety is common.","exampleZh":"考试焦虑很常见。"},
{"word":"anxious","ipa":"/ˈæŋkʃəs/","pos":"adj.","cat":"cet4","meaning":"焦虑的；渴望的","example":"She is anxious about the result.","exampleZh":"她对结果感到焦虑。"},
{"word":"apart","ipa":"/əˈpɑːrt/","pos":"adv.","cat":"cet4","meaning":"分开；相隔","example":"The two houses stand far apart.","exampleZh":"两栋房子相距很远。"},
{"word":"apartment","ipa":"/əˈpɑːrtmənt/","pos":"n.","cat":"cet4","meaning":"公寓","example":"They rented a small apartment.","exampleZh":"他们租了一间小公寓。"},
{"word":"apologize","ipa":"/əˈpɒlədʒaɪz/","pos":"v.","cat":"cet4","meaning":"道歉","example":"I apologized for being late.","exampleZh":"我为迟到道歉。"},
{"word":"apparent","ipa":"/əˈpærənt/","pos":"adj.","cat":"cet4","meaning":"明显的；表面的","example":"His joy was apparent.","exampleZh":"他的喜悦显而易见。"},
{"word":"appeal","ipa":"/əˈpiːl/","pos":"v./n.","cat":"cet4","meaning":"呼吁；吸引；上诉","example":"The idea appeals to young people.","exampleZh":"这个想法吸引年轻人。"},
{"word":"appear","ipa":"/əˈpɪr/","pos":"v.","cat":"cet4","meaning":"出现；似乎","example":"A solution appeared at last.","exampleZh":"终于出现了解决办法。"},
{"word":"applause","ipa":"/əˈplɔːz/","pos":"n.","cat":"cet4","meaning":"掌声","example":"The speech won warm applause.","exampleZh":"演讲赢得了热烈掌声。"},
{"word":"applicant","ipa":"/ˈæplɪkənt/","pos":"n.","cat":"cet4","meaning":"申请人","example":"There were many applicants.","exampleZh":"有很多申请人。"},
{"word":"application","ipa":"/ˌæplɪˈkeɪʃn/","pos":"n.","cat":"cet4","meaning":"申请；应用","example":"Please submit your application.","exampleZh":"请提交你的申请。"},
{"word":"apply","ipa":"/əˈplaɪ/","pos":"v.","cat":"cet4","meaning":"申请；应用","example":"Apply the rule to this case.","exampleZh":"把这条规则用到这个案例上。"},
{"word":"appoint","ipa":"/əˈpɔɪnt/","pos":"v.","cat":"cet4","meaning":"任命；约定","example":"He was appointed manager.","exampleZh":"他被任命为经理。"},
{"word":"appreciate","ipa":"/əˈpriːʃieɪt/","pos":"v.","cat":"cet4","meaning":"欣赏；感激","example":"I appreciate your help.","exampleZh":"感谢你的帮助。"},
{"word":"approach","ipa":"/əˈproʊtʃ/","pos":"v./n.","cat":"cet4","meaning":"接近；方法","example":"We need a new approach.","exampleZh":"我们需要新方法。"},
{"word":"appropriate","ipa":"/əˈproʊpriət/","pos":"adj.","cat":"cet4","meaning":"合适的","example":"Wear appropriate clothes.","exampleZh":"穿得体的衣服。"},
{"word":"approve","ipa":"/əˈpruːv/","pos":"v.","cat":"cet4","meaning":"批准；赞成","example":"The board approved the plan.","exampleZh":"董事会批准了计划。"},
{"word":"area","ipa":"/ˈeriə/","pos":"n.","cat":"cet4","meaning":"地区；面积","example":"This area is safe at night.","exampleZh":"这一带夜里很安全。"},
{"word":"argue","ipa":"/ˈɑːrɡjuː/","pos":"v.","cat":"cet4","meaning":"争论；主张","example":"They argued about the price.","exampleZh":"他们就价格争论起来。"},
{"word":"arise","ipa":"/əˈraɪz/","pos":"v.","cat":"cet4","meaning":"出现；升起","example":"A problem arose yesterday.","exampleZh":"昨天出现了一个问题。"},
{"word":"arm","ipa":"/ɑːrm/","pos":"n./v.","cat":"cet4","meaning":"手臂；武装","example":"The police armed themselves.","exampleZh":"警察武装了自己。"},
{"word":"arrange","ipa":"/əˈreɪndʒ/","pos":"v.","cat":"cet4","meaning":"安排；整理","example":"She arranged a meeting.","exampleZh":"她安排了一次会议。"},
{"word":"arrest","ipa":"/əˈrest/","pos":"v./n.","cat":"cet4","meaning":"逮捕","example":"The suspect was arrested.","exampleZh":"嫌疑人被逮捕了。"},
{"word":"article","ipa":"/ˈɑːrtɪkl/","pos":"n.","cat":"cet4","meaning":"文章；物品；条款","example":"I read an article on health.","exampleZh":"我读了一篇关于健康的文章。"},
{"word":"artificial","ipa":"/ˌɑːrtɪˈfɪʃl/","pos":"adj.","cat":"cet4","meaning":"人造的；假的","example":"The lake is artificial.","exampleZh":"这个湖是人造的。"},
{"word":"aspect","ipa":"/ˈæspekt/","pos":"n.","cat":"cet4","meaning":"方面","example":"We studied every aspect.","exampleZh":"我们研究了每个方面。"},
{"word":"assess","ipa":"/əˈses/","pos":"v.","cat":"cet4","meaning":"评估；评定","example":"They assessed the risk.","exampleZh":"他们评估了风险。"},
{"word":"assign","ipa":"/əˈsaɪn/","pos":"v.","cat":"cet4","meaning":"分配；指派","example":"The teacher assigned homework.","exampleZh":"老师布置了作业。"},
{"word":"assist","ipa":"/əˈsɪst/","pos":"v.","cat":"cet4","meaning":"协助","example":"Two nurses assisted the doctor.","exampleZh":"两名护士协助医生。"},
{"word":"associate","ipa":"/əˈsoʊʃieɪt/","pos":"v.","cat":"cet4","meaning":"联想；联系；交往","example":"We associate spring with hope.","exampleZh":"我们把春天和希望联系在一起。"},
{"word":"assume","ipa":"/əˈsuːm/","pos":"v.","cat":"cet4","meaning":"假定；承担","example":"I assume you agree.","exampleZh":"我猜你同意。"},
{"word":"assure","ipa":"/əˈʃʊr/","pos":"v.","cat":"cet4","meaning":"向…保证；使确信","example":"He assured me it was safe.","exampleZh":"他向我保证这很安全。"},
{"word":"atmosphere","ipa":"/ˈætməsfɪr/","pos":"n.","cat":"cet4","meaning":"大气；氛围","example":"The atmosphere was festive.","exampleZh":"氛围很喜庆。"},
{"word":"attach","ipa":"/əˈtætʃ/","pos":"v.","cat":"cet4","meaning":"附上；系","example":"Please attach the file.","exampleZh":"请附上文件。"},
{"word":"attack","ipa":"/əˈtæk/","pos":"v./n.","cat":"cet4","meaning":"攻击；抨击","example":"The dog attacked the stranger.","exampleZh":"狗袭击了陌生人。"},
{"word":"attain","ipa":"/əˈteɪn/","pos":"v.","cat":"cet4","meaning":"达到；获得","example":"She attained her goal.","exampleZh":"她达到了目标。"},
{"word":"attempt","ipa":"/əˈtempt/","pos":"v./n.","cat":"cet4","meaning":"尝试；企图","example":"They attempted to escape.","exampleZh":"他们试图逃跑。"},
{"word":"attend","ipa":"/əˈtend/","pos":"v.","cat":"cet4","meaning":"出席；照料","example":"He attended the lecture.","exampleZh":"他听了讲座。"},
{"word":"attitude","ipa":"/ˈætɪtuːd/","pos":"n.","cat":"cet4","meaning":"态度","example":"Her attitude changed.","exampleZh":"她的态度变了。"},
{"word":"attract","ipa":"/əˈtrækt/","pos":"v.","cat":"cet4","meaning":"吸引","example":"The show attracted a crowd.","exampleZh":"演出吸引了一群人。"},
{"word":"audience","ipa":"/ˈɔːdiəns/","pos":"n.","cat":"cet4","meaning":"观众；听众","example":"The audience applauded.","exampleZh":"观众鼓掌。"},
{"word":"author","ipa":"/ˈɔːθər/","pos":"n.","cat":"cet4","meaning":"作者","example":"The author wrote a novel.","exampleZh":"这位作者写了一本小说。"},
{"word":"authority","ipa":"/əˈθɔːrəti/","pos":"n.","cat":"cet4","meaning":"权威；当局","example":"The authority banned the trade.","exampleZh":"当局禁止了该交易。"},
{"word":"automatic","ipa":"/ˌɔːtəˈmætɪk/","pos":"adj.","cat":"cet4","meaning":"自动的","example":"The door is automatic.","exampleZh":"这扇门是自动的。"},
{"word":"available","ipa":"/əˈveɪləbl/","pos":"adj.","cat":"cet4","meaning":"可获得的；有空的","example":"Is the manager available?","exampleZh":"经理有空吗？"},
{"word":"average","ipa":"/ˈævərɪdʒ/","pos":"adj./n.","cat":"cet4","meaning":"平均的；平均数","example":"The average score rose.","exampleZh":"平均分提高了。"},
{"word":"avoid","ipa":"/əˈvɔɪd/","pos":"v.","cat":"cet4","meaning":"避免","example":"Avoid making the same mistake.","exampleZh":"避免犯同样的错。"},
{"word":"award","ipa":"/əˈwɔːrd/","pos":"n./v.","cat":"cet4","meaning":"奖；授予","example":"He won an award.","exampleZh":"他得了一个奖。"},
{"word":"aware","ipa":"/əˈwer/","pos":"adj.","cat":"cet4","meaning":"意识到的","example":"Are you aware of the risk?","exampleZh":"你意识到风险了吗？"},
{"word":"awful","ipa":"/ˈɔːfl/","pos":"adj.","cat":"cet4","meaning":"糟糕的；可怕的","example":"The weather was awful.","exampleZh":"天气糟透了。"},
{"word":"background","ipa":"/ˈbækɡraʊnd/","pos":"n.","cat":"cet4","meaning":"背景","example":"He has a legal background.","exampleZh":"他有法律背景。"},
{"word":"balance","ipa":"/ˈbæləns/","pos":"n./v.","cat":"cet4","meaning":"平衡；权衡","example":"Keep a balance between work and life.","exampleZh":"平衡工作与生活。"},
{"word":"barely","ipa":"/ˈberli/","pos":"adv.","cat":"cet4","meaning":"仅仅；几乎不","example":"We barely finished in time.","exampleZh":"我们勉强按时完成。"},
{"word":"barrier","ipa":"/ˈbæriər/","pos":"n.","cat":"cet4","meaning":"障碍；屏障","example":"Language is a barrier.","exampleZh":"语言是一道障碍。"},
{"word":"basis","ipa":"/ˈbeɪsɪs/","pos":"n.","cat":"cet4","meaning":"基础；根据","example":"Trust is the basis of friendship.","exampleZh":"信任是友谊的基础。"},
{"word":"behave","ipa":"/bɪˈheɪv/","pos":"v.","cat":"cet4","meaning":"表现；举止","example":"The child behaved well.","exampleZh":"这孩子表现很好。"},
{"word":"behavior","ipa":"/bɪˈheɪvjər/","pos":"n.","cat":"cet4","meaning":"行为","example":"His behavior surprised us.","exampleZh":"他的行为让我们惊讶。"},
{"word":"belief","ipa":"/bɪˈliːf/","pos":"n.","cat":"cet4","meaning":"信念；相信","example":"It is my firm belief.","exampleZh":"这是我坚定的信念。"},
{"word":"believe","ipa":"/bɪˈliːv/","pos":"v.","cat":"cet4","meaning":"相信","example":"I believe in you.","exampleZh":"我相信你。"},
{"word":"benefit","ipa":"/ˈbenɪfɪt/","pos":"n./v.","cat":"cet4","meaning":"益处；受益","example":"Exercise benefits health.","exampleZh":"运动有益健康。"},
{"word":"beyond","ipa":"/bɪˈjɒnd/","pos":"prep.","cat":"cet4","meaning":"超出；在…那一边","example":"It is beyond my control.","exampleZh":"这超出了我的掌控。"},
{"word":"blame","ipa":"/bleɪm/","pos":"v./n.","cat":"cet4","meaning":"责备；责任","example":"Don't blame yourself.","exampleZh":"别责怪自己。"},
{"word":"bond","ipa":"/bɒnd/","pos":"n.","cat":"cet4","meaning":"纽带；债券","example":"The bond between them is strong.","exampleZh":"他们的纽带很牢固。"},
{"word":"boost","ipa":"/buːst/","pos":"v./n.","cat":"cet4","meaning":"提升；推动","example":"The ad boosted sales.","exampleZh":"广告提振了销量。"},
{"word":"border","ipa":"/ˈbɔːrdər/","pos":"n.","cat":"cet4","meaning":"边界；边境","example":"They crossed the border.","exampleZh":"他们越过了边境。"},
{"word":"bore","ipa":"/bɔːr/","pos":"v.","cat":"cet4","meaning":"使厌烦","example":"The lecture bored me.","exampleZh":"讲座让我觉得无聊。"},
{"word":"branch","ipa":"/brɑːntʃ/","pos":"n.","cat":"cet4","meaning":"分支；树枝","example":"The bank opened a new branch.","exampleZh":"银行开了新支行。"},
{"word":"brand","ipa":"/brænd/","pos":"n.","cat":"cet4","meaning":"品牌","example":"This brand is popular.","exampleZh":"这个品牌很受欢迎。"},
{"word":"breath","ipa":"/breθ/","pos":"n.","cat":"cet4","meaning":"呼吸；气息","example":"Take a deep breath.","exampleZh":"深呼吸一下。"},
{"word":"breathe","ipa":"/briːð/","pos":"v.","cat":"cet4","meaning":"呼吸","example":"Breathe slowly and relax.","exampleZh":"慢慢呼吸，放松。"},
{"word":"brief","ipa":"/briːf/","pos":"adj.","cat":"cet4","meaning":"简短的","example":"Give me a brief summary.","exampleZh":"给我一个简短的总结。"},
{"word":"broad","ipa":"/brɔːd/","pos":"adj.","cat":"cet4","meaning":"宽阔的；广泛的","example":"He has broad shoulders.","exampleZh":"他肩膀宽阔。"},
{"word":"budget","ipa":"/ˈbʌdʒɪt/","pos":"n./v.","cat":"cet4","meaning":"预算","example":"We exceeded the budget.","exampleZh":"我们超预算了。"},
{"word":"burden","ipa":"/ˈbɜːrdn/","pos":"n./v.","cat":"cet4","meaning":"负担","example":"The debt is a heavy burden.","exampleZh":"债务是沉重负担。"},
{"word":"calculate","ipa":"/ˈkælkjuleɪt/","pos":"v.","cat":"cet4","meaning":"计算","example":"Calculate the total cost.","exampleZh":"算一下总成本。"},
{"word":"campaign","ipa":"/kæmˈpeɪn/","pos":"n.","cat":"cet4","meaning":"运动；战役","example":"A health campaign launched.","exampleZh":"一场健康运动启动了。"},
{"word":"candidate","ipa":"/ˈkændɪdət/","pos":"n.","cat":"cet4","meaning":"候选人","example":"She is a strong candidate.","exampleZh":"她是个强有力的候选人。"},
{"word":"capable","ipa":"/ˈkeɪpəbl/","pos":"adj.","cat":"cet4","meaning":"有能力的","example":"He is capable of leadership.","exampleZh":"他有领导能力。"},
{"word":"capacity","ipa":"/kəˈpæsəti/","pos":"n.","cat":"cet4","meaning":"容量；能力","example":"The hall has a capacity of 500.","exampleZh":"大厅容量为500人。"},
{"word":"career","ipa":"/kəˈrɪr/","pos":"n.","cat":"cet4","meaning":"职业；生涯","example":"She built a career in law.","exampleZh":"她从事法律职业。"},
{"word":"casual","ipa":"/ˈkæʒuəl/","pos":"adj.","cat":"cet4","meaning":"随意的；非正式的","example":"He wore casual clothes.","exampleZh":"他穿着休闲装。"},
{"word":"catalog","ipa":"/ˈkætəlɔːɡ/","pos":"n./v.","cat":"cet4","meaning":"目录；编目","example":"Browse the online catalog.","exampleZh":"浏览在线目录。"},
{"word":"cause","ipa":"/kɔːz/","pos":"n./v.","cat":"cet4","meaning":"原因；导致","example":"The storm caused damage.","exampleZh":"暴风雨造成了破坏。"},
{"word":"cease","ipa":"/siːs/","pos":"v.","cat":"cet4","meaning":"停止","example":"The fighting ceased.","exampleZh":"战斗停止了。"},
{"word":"challenge","ipa":"/ˈtʃælɪndʒ/","pos":"n./v.","cat":"cet4","meaning":"挑战","example":"This is a real challenge.","exampleZh":"这是个真正的挑战。"},
{"word":"channel","ipa":"/ˈtʃænl/","pos":"n.","cat":"cet4","meaning":"频道；渠道","example":"Use the official channel.","exampleZh":"走官方渠道。"},
{"word":"character","ipa":"/ˈkærəktər/","pos":"n.","cat":"cet4","meaning":"性格；角色；字符","example":"He is a man of character.","exampleZh":"他是个有品格的人。"},
{"word":"charge","ipa":"/tʃɑːrdʒ/","pos":"n./v.","cat":"cet4","meaning":"收费；指控；充电","example":"They charged a fee.","exampleZh":"他们收了费。"},
{"word":"circumstance","ipa":"/ˈsɜːrkəmstæns/","pos":"n.","cat":"cet4","meaning":"情况；环境","example":"Under no circumstance should you lie.","exampleZh":"无论如何你都不该撒谎。"},
{"word":"civil","ipa":"/ˈsɪvl/","pos":"adj.","cat":"cet4","meaning":"公民的；民用的","example":"Civil rights protect us.","exampleZh":"公民权利保护我们。"},
{"word":"claim","ipa":"/kleɪm/","pos":"v./n.","cat":"cet4","meaning":"声称；要求；索赔","example":"He claimed the reward.","exampleZh":"他领取了奖励。"},
{"word":"classic","ipa":"/ˈklæsɪk/","pos":"adj./n.","cat":"cet4","meaning":"经典的；名著","example":"This is a classic novel.","exampleZh":"这是一部经典小说。"},
{"word":"climate","ipa":"/ˈklaɪmət/","pos":"n.","cat":"cet4","meaning":"气候","example":"The climate is changing.","exampleZh":"气候正在变化。"},
{"word":"coach","ipa":"/koʊtʃ/","pos":"n./v.","cat":"cet4","meaning":"教练；指导","example":"The coach trained the team.","exampleZh":"教练训练了队伍。"},
{"word":"collapse","ipa":"/kəˈlæps/","pos":"v./n.","cat":"cet4","meaning":"倒塌；崩溃","example":"The bridge collapsed.","exampleZh":"桥塌了。"},
{"word":"combine","ipa":"/kəmˈbaɪn/","pos":"v.","cat":"cet4","meaning":"结合","example":"Combine work and study.","exampleZh":"把工作与学习结合起来。"},
{"word":"commit","ipa":"/kəˈmɪt/","pos":"v.","cat":"cet4","meaning":"承诺；犯（错）","example":"He committed to the plan.","exampleZh":"他承诺执行计划。"},
{"word":"community","ipa":"/kəˈmjuːnəti/","pos":"n.","cat":"cet4","meaning":"社区；群体","example":"The community supported us.","exampleZh":"社区支持了我们。"},
{"word":"compare","ipa":"/kəmˈper/","pos":"v.","cat":"cet4","meaning":"比较","example":"Compare the two options.","exampleZh":"比较这两个选项。"},
{"word":"compete","ipa":"/kəmˈpiːt/","pos":"v.","cat":"cet4","meaning":"竞争","example":"They compete for the prize.","exampleZh":"他们为奖品竞争。"},
{"word":"complex","ipa":"/ˈkɒmpleks/","pos":"adj.","cat":"cet4","meaning":"复杂的","example":"The system is complex.","exampleZh":"系统很复杂。"},
{"word":"concept","ipa":"/ˈkɒnsept/","pos":"n.","cat":"cet4","meaning":"概念","example":"Explain the key concept.","exampleZh":"解释一下关键概念。"},
{"word":"conduct","ipa":"/kənˈdʌkt/","pos":"v.","cat":"cet4","meaning":"实施；引导","example":"We conducted a survey.","exampleZh":"我们做了一项调查。"},
{"word":"confidence","ipa":"/ˈkɒnfɪdəns/","pos":"n.","cat":"cet4","meaning":"信心","example":"She spoke with confidence.","exampleZh":"她自信地发言。"},
{"word":"confirm","ipa":"/kənˈfɜːrm/","pos":"v.","cat":"cet4","meaning":"确认","example":"Please confirm your order.","exampleZh":"请确认你的订单。"},
{"word":"conflict","ipa":"/ˈkɒnflɪkt/","pos":"n./v.","cat":"cet4","meaning":"冲突","example":"A conflict arose.","exampleZh":"出现了冲突。"},
{"word":"connect","ipa":"/kəˈnekt/","pos":"v.","cat":"cet4","meaning":"连接","example":"Connect the cable.","exampleZh":"接上电缆。"},
{"word":"consent","ipa":"/kənˈsent/","pos":"n./v.","cat":"cet4","meaning":"同意；准许","example":"He gave his consent.","exampleZh":"他同意了。"},
{"word":"consist","ipa":"/kənˈsɪst/","pos":"v.","cat":"cet4","meaning":"由…组成","example":"The team consists of five.","exampleZh":"团队由五人组成。"},
{"word":"constant","ipa":"/ˈkɒnstənt/","pos":"adj.","cat":"cet4","meaning":"持续的；恒定的","example":"The noise is constant.","exampleZh":"噪音持续不断。"},
{"word":"construct","ipa":"/kənˈstrʌkt/","pos":"v.","cat":"cet4","meaning":"建造；构建","example":"They constructed a bridge.","exampleZh":"他们建了一座桥。"},
{"word":"consult","ipa":"/kənˈsʌlt/","pos":"v.","cat":"cet4","meaning":"咨询；查阅","example":"Consult a doctor.","exampleZh":"咨询医生。"},
{"word":"consume","ipa":"/kənˈsjuːm/","pos":"v.","cat":"cet4","meaning":"消耗；消费","example":"The device consumes little power.","exampleZh":"这设备耗电很少。"},
{"word":"contact","ipa":"/ˈkɒntækt/","pos":"n./v.","cat":"cet4","meaning":"联系；接触","example":"Contact me by email.","exampleZh":"用邮件联系我。"},
{"word":"contain","ipa":"/kənˈteɪn/","pos":"v.","cat":"cet4","meaning":"包含；容纳","example":"The box contains books.","exampleZh":"盒子里装着书。"},
{"word":"contemporary","ipa":"/kənˈtemprəri/","pos":"adj.","cat":"cet4","meaning":"当代的；同时代的","example":"She likes contemporary art.","exampleZh":"她喜欢当代艺术。"},
{"word":"context","ipa":"/ˈkɒntekst/","pos":"n.","cat":"cet4","meaning":"语境；背景","example":"Read it in context.","exampleZh":"结合语境读。"},
{"word":"contrast","ipa":"/ˈkɒntræst/","pos":"n./v.","cat":"cet4","meaning":"对比；对照","example":"The contrast is clear.","exampleZh":"对比很明显。"},
{"word":"contribute","ipa":"/kənˈtrɪbjuːt/","pos":"v.","cat":"cet4","meaning":"贡献；投稿","example":"She contributed to the fund.","exampleZh":"她为基金捐款。"},
{"word":"controversy","ipa":"/ˈkɒntrəvɜːrsi/","pos":"n.","cat":"cet4","meaning":"争议","example":"The plan sparked controversy.","exampleZh":"该计划引发争议。"},
{"word":"convince","ipa":"/kənˈvɪns/","pos":"v.","cat":"cet4","meaning":"使信服","example":"I convinced him to stay.","exampleZh":"我说服他留下。"},
{"word":"cooperate","ipa":"/koʊˈɒpəreɪt/","pos":"v.","cat":"cet4","meaning":"合作","example":"They cooperated on the project.","exampleZh":"他们在项目上合作。"},
{"word":"corporate","ipa":"/ˈkɔːrpərət/","pos":"adj.","cat":"cet4","meaning":"公司的；法人的","example":"The corporate office is downtown.","exampleZh":"公司总部在市中心。"}
];
