// 离线词库分片 5/5（由 split_offline_dict.js 生成，勿手改）
var OFFLINE_EXTRA_5 = [
{"word":"specific","ipa":"/spəˈsɪfɪk/","pos":"adj.","cat":"cet4","meaning":"具体的；特定的","example":"Be specific.","exampleZh":"说具体点。"},
{"word":"specify","ipa":"/ˈspesɪfaɪ/","pos":"v.","cat":"cet4","meaning":"明确说明","example":"Specify the date.","exampleZh":"明确日期。"},
{"word":"spite","ipa":"/spaɪt/","pos":"n.","cat":"cet4","meaning":"恶意","example":"In spite of the rain.","exampleZh":"尽管下雨。"},
{"word":"split","ipa":"/splɪt/","pos":"v.","cat":"cet4","meaning":"分裂；分开","example":"Split the bill.","exampleZh":"分摊账单。"},
{"word":"sponsor","ipa":"/ˈspɒnsər/","pos":"n./v.","cat":"cet4","meaning":"赞助者；赞助","example":"A corporate sponsor.","exampleZh":"企业赞助商。"},
{"word":"spot","ipa":"/spɒt/","pos":"n./v.","cat":"cet4","meaning":"地点；发现","example":"I spotted an error.","exampleZh":"我发现了一个错误。"},
{"word":"stable","ipa":"/ˈsteɪbl/","pos":"adj.","cat":"cet4","meaning":"稳定的","example":"A stable economy.","exampleZh":"稳定的经济。"},
{"word":"statistic","ipa":"/stəˈtɪstɪk/","pos":"n.","cat":"cet4","meaning":"统计数字","example":"The statistic surprised us.","exampleZh":"这个统计数字让我们惊讶。"},
{"word":"status","ipa":"/ˈsteɪtəs/","pos":"n.","cat":"cet4","meaning":"地位；状态","example":"Check the status.","exampleZh":"查看状态。"},
{"word":"steady","ipa":"/ˈstedi/","pos":"adj.","cat":"cet4","meaning":"稳定的","example":"A steady hand.","exampleZh":"稳健的手。"},
{"word":"stick","ipa":"/stɪk/","pos":"v.","cat":"cet4","meaning":"粘；坚持","example":"Stick to the plan.","exampleZh":"坚持计划。"},
{"word":"stimulate","ipa":"/ˈstɪmjuleɪt/","pos":"v.","cat":"cet4","meaning":"刺激；激励","example":"The policy stimulates growth.","exampleZh":"政策刺激增长。"},
{"word":"stir","ipa":"/stɜːr/","pos":"v.","cat":"cet4","meaning":"搅拌；激起","example":"Stir the soup.","exampleZh":"搅一下汤。"},
{"word":"strategy","ipa":"/ˈstrætədʒi/","pos":"n.","cat":"cet4","meaning":"战略","example":"A clear strategy.","exampleZh":"清晰的战略。"},
{"word":"strength","ipa":"/streŋθ/","pos":"n.","cat":"cet4","meaning":"力量；长处","example":"Build your strength.","exampleZh":"增强力量。"},
{"word":"stress","ipa":"/stres/","pos":"n./v.","cat":"cet4","meaning":"压力；强调","example":"He is under stress.","exampleZh":"他压力大。"},
{"word":"strict","ipa":"/strɪkt/","pos":"adj.","cat":"cet4","meaning":"严格的","example":"A strict teacher.","exampleZh":"严格的老师。"},
{"word":"strike","ipa":"/straɪk/","pos":"v./n.","cat":"cet4","meaning":"罢工；打击","example":"Workers went on strike.","exampleZh":"工人罢工了。"},
{"word":"string","ipa":"/strɪŋ/","pos":"n.","cat":"cet4","meaning":"细绳；字符串","example":"A string of beads.","exampleZh":"一串珠子。"},
{"word":"structure","ipa":"/ˈstrʌktʃər/","pos":"n.","cat":"cet4","meaning":"结构","example":"The sentence structure.","exampleZh":"句子结构。"},
{"word":"struggle","ipa":"/ˈstrʌɡl/","pos":"v./n.","cat":"cet4","meaning":"挣扎；奋斗","example":"They struggled to survive.","exampleZh":"他们挣扎求生。"},
{"word":"submit","ipa":"/səbˈmɪt/","pos":"v.","cat":"cet4","meaning":"提交；服从","example":"Submit the form.","exampleZh":"提交表格。"},
{"word":"subsequent","ipa":"/ˈsʌbsɪkwənt/","pos":"adj.","cat":"cet4","meaning":"随后的","example":"Subsequent events.","exampleZh":"随后的事件。"},
{"word":"substance","ipa":"/ˈsʌbstəns/","pos":"n.","cat":"cet4","meaning":"物质；实质","example":"A harmful substance.","exampleZh":"有害物质。"},
{"word":"substantial","ipa":"/səbˈstænʃl/","pos":"adj.","cat":"cet4","meaning":"大量的；实质性的","example":"A substantial sum.","exampleZh":"一笔巨款。"},
{"word":"subtle","ipa":"/ˈsʌtl/","pos":"adj.","cat":"cet4","meaning":"微妙的","example":"A subtle difference.","exampleZh":"细微的差别。"},
{"word":"successor","ipa":"/səkˈsesər/","pos":"n.","cat":"cet4","meaning":"继任者","example":"The CEO's successor.","exampleZh":"CEO的继任者。"},
{"word":"suffer","ipa":"/ˈsʌfər/","pos":"v.","cat":"cet4","meaning":"遭受；受苦","example":"He suffered a loss.","exampleZh":"他遭受了损失。"},
{"word":"sufficient","ipa":"/səˈfɪʃnt/","pos":"adj.","cat":"cet4","meaning":"足够的","example":"Is it sufficient?","exampleZh":"这够吗？"},
{"word":"suggest","ipa":"/səˈdʒest/","pos":"v.","cat":"cet4","meaning":"建议；暗示","example":"I suggest a break.","exampleZh":"我建议休息一下。"},
{"word":"summary","ipa":"/ˈsʌməri/","pos":"n.","cat":"cet4","meaning":"摘要","example":"Give a summary.","exampleZh":"给个摘要。"},
{"word":"summit","ipa":"/ˈsʌmɪt/","pos":"n.","cat":"cet4","meaning":"峰会；顶峰","example":"A global summit.","exampleZh":"全球峰会。"},
{"word":"superb","ipa":"/suːˈpɜːrb/","pos":"adj.","cat":"cet4","meaning":"极好的","example":"A superb meal.","exampleZh":"一顿美餐。"},
{"word":"superficial","ipa":"/ˌsuːpərˈfɪʃl/","pos":"adj.","cat":"cet4","meaning":"表面的","example":"A superficial wound.","exampleZh":"表皮伤。"},
{"word":"supplement","ipa":"/ˈsʌplɪment/","pos":"n./v.","cat":"cet4","meaning":"补充","example":"Take a supplement.","exampleZh":"补充营养剂。"},
{"word":"supply","ipa":"/səˈplaɪ/","pos":"n./v.","cat":"cet4","meaning":"供应","example":"Supply meets demand.","exampleZh":"供需平衡。"},
{"word":"suppose","ipa":"/səˈpoʊz/","pos":"v.","cat":"cet4","meaning":"假设；认为","example":"I suppose so.","exampleZh":"我想是吧。"},
{"word":"supreme","ipa":"/suːˈpriːm/","pos":"adj.","cat":"cet4","meaning":"最高的；至上的","example":"The supreme court.","exampleZh":"最高法院。"},
{"word":"surface","ipa":"/ˈsɜːrfɪs/","pos":"n.","cat":"cet4","meaning":"表面","example":"The water surface.","exampleZh":"水面。"},
{"word":"surge","ipa":"/sɜːrdʒ/","pos":"n./v.","cat":"cet4","meaning":"激增；汹涌","example":"A surge in demand.","exampleZh":"需求激增。"},
{"word":"surplus","ipa":"/ˈsɜːrpləs/","pos":"n.","cat":"cet4","meaning":"盈余","example":"A trade surplus.","exampleZh":"贸易顺差。"},
{"word":"surround","ipa":"/səˈraʊnd/","pos":"v.","cat":"cet4","meaning":"环绕","example":"Trees surround the house.","exampleZh":"树环绕着房子。"},
{"word":"survey","ipa":"/ˈsɜːrveɪ/","pos":"n./v.","cat":"cet4","meaning":"调查；测绘","example":"A customer survey.","exampleZh":"客户调查。"},
{"word":"survive","ipa":"/sərˈvaɪv/","pos":"v.","cat":"cet4","meaning":"幸存","example":"Few survived.","exampleZh":"很少有人幸存。"},
{"word":"suspect","ipa":"/səˈspekt/","pos":"v./n.","cat":"cet4","meaning":"怀疑；嫌疑犯","example":"He suspected a lie.","exampleZh":"他怀疑有谎言。"},
{"word":"suspend","ipa":"/səˈspend/","pos":"v.","cat":"cet4","meaning":"暂停；悬浮","example":"The game was suspended.","exampleZh":"比赛被暂停。"},
{"word":"sustain","ipa":"/səˈsteɪn/","pos":"v.","cat":"cet4","meaning":"维持；支撑","example":"Sustain the effort.","exampleZh":"坚持努力。"},
{"word":"swallow","ipa":"/ˈswɒloʊ/","pos":"v.","cat":"cet4","meaning":"吞；轻信","example":"Swallow the pill.","exampleZh":"吞下药丸。"},
{"word":"sway","ipa":"/sweɪ/","pos":"v.","cat":"cet4","meaning":"摇摆；影响","example":"The wind swayed the trees.","exampleZh":"风摇动树木。"},
{"word":"swear","ipa":"/swer/","pos":"v.","cat":"cet4","meaning":"发誓；咒骂","example":"He swore to tell the truth.","exampleZh":"他发誓说实话。"},
{"word":"sweat","ipa":"/swet/","pos":"n./v.","cat":"cet4","meaning":"汗；出汗","example":"He broke into a sweat.","exampleZh":"他出了汗。"},
{"word":"swell","ipa":"/swel/","pos":"v.","cat":"cet4","meaning":"膨胀；肿胀","example":"The river swelled.","exampleZh":"河水上涨。"},
{"word":"swift","ipa":"/swɪft/","pos":"adj.","cat":"cet4","meaning":"迅速的","example":"A swift response.","exampleZh":"迅速的回应。"},
{"word":"swing","ipa":"/swɪŋ/","pos":"v./n.","cat":"cet4","meaning":"摇摆；秋千","example":"The door swung open.","exampleZh":"门晃开了。"},
{"word":"switch","ipa":"/swɪtʃ/","pos":"n./v.","cat":"cet4","meaning":"开关；切换","example":"Switch the light.","exampleZh":"开灯。"},
{"word":"symbol","ipa":"/ˈsɪmbl/","pos":"n.","cat":"cet4","meaning":"象征；符号","example":"A symbol of peace.","exampleZh":"和平的象征。"},
{"word":"sympathy","ipa":"/ˈsɪmpəθi/","pos":"n.","cat":"cet4","meaning":"同情","example":"She felt sympathy.","exampleZh":"她感到同情。"},
{"word":"symptom","ipa":"/ˈsɪmptəm/","pos":"n.","cat":"cet4","meaning":"症状","example":"A cold symptom.","exampleZh":"感冒症状。"},
{"word":"tackle","ipa":"/ˈtækl/","pos":"v.","cat":"cet4","meaning":"处理； tackle","example":"Tackle the problem.","exampleZh":"处理问题。"},
{"word":"talent","ipa":"/ˈtælənt/","pos":"n.","cat":"cet4","meaning":"天赋","example":"She has talent.","exampleZh":"她有天赋。"},
{"word":"target","ipa":"/ˈtɑːrɡɪt/","pos":"n./v.","cat":"cet4","meaning":"目标；瞄准","example":"Meet the target.","exampleZh":"达成目标。"},
{"word":"tax","ipa":"/tæks/","pos":"n./v.","cat":"cet4","meaning":"税；征税","example":"Pay your tax.","exampleZh":"交税。"},
{"word":"technical","ipa":"/ˈteknɪkl/","pos":"adj.","cat":"cet4","meaning":"技术的","example":"A technical issue.","exampleZh":"技术问题。"},
{"word":"technique","ipa":"/tekˈniːk/","pos":"n.","cat":"cet4","meaning":"技巧","example":"A new technique.","exampleZh":"新技术。"},
{"word":"temporary","ipa":"/ˈtemprəri/","pos":"adj.","cat":"cet4","meaning":"临时的","example":"A temporary job.","exampleZh":"临时工作。"},
{"word":"tempt","ipa":"/tempt/","pos":"v.","cat":"cet4","meaning":"诱惑","example":"Do not tempt fate.","exampleZh":"别冒险。"},
{"word":"tend","ipa":"/tend/","pos":"v.","cat":"cet4","meaning":"倾向于","example":"I tend to agree.","exampleZh":"我倾向于同意。"},
{"word":"tension","ipa":"/ˈtenʃn/","pos":"n.","cat":"cet4","meaning":"紧张；张力","example":"Ease the tension.","exampleZh":"缓解紧张。"},
{"word":"terminal","ipa":"/ˈtɜːrmɪnl/","pos":"n./adj.","cat":"cet4","meaning":"终点站；晚期的","example":"The bus terminal.","exampleZh":"公交总站。"},
{"word":"territory","ipa":"/ˈterətɔːri/","pos":"n.","cat":"cet4","meaning":"领土；领域","example":"Defend the territory.","exampleZh":"保卫领土。"},
{"word":"terror","ipa":"/ˈterər/","pos":"n.","cat":"cet4","meaning":"恐怖","example":"A terror attack.","exampleZh":"恐怖袭击。"},
{"word":"theme","ipa":"/θiːm/","pos":"n.","cat":"cet4","meaning":"主题","example":"The theme of the book.","exampleZh":"书的主题。"},
{"word":"theory","ipa":"/ˈθɪəri/","pos":"n.","cat":"cet4","meaning":"理论","example":"In theory.","exampleZh":"理论上。"},
{"word":"thereby","ipa":"/ˌðerˈbaɪ/","pos":"adv.","cat":"cet4","meaning":"从而","example":"He left, thereby ending it.","exampleZh":"他离开，从而结束了。"},
{"word":"therefore","ipa":"/ˈðerfɔːr/","pos":"adv.","cat":"cet4","meaning":"因此","example":"It rained; therefore we stayed.","exampleZh":"下雨了，因此我们留下。"},
{"word":"thorough","ipa":"/ˈθʌroʊ/","pos":"adj.","cat":"cet4","meaning":"彻底的","example":"A thorough check.","exampleZh":"彻底的检查。"},
{"word":"threat","ipa":"/θret/","pos":"n.","cat":"cet4","meaning":"威胁","example":"A security threat.","exampleZh":"安全威胁。"},
{"word":"thrill","ipa":"/θrɪl/","pos":"n./v.","cat":"cet4","meaning":"兴奋；使激动","example":"The news thrilled us.","exampleZh":"消息让我们激动。"},
{"word":"thrive","ipa":"/θraɪv/","pos":"v.","cat":"cet4","meaning":"繁荣；茁壮成长","example":"Plants thrive in spring.","exampleZh":"植物在春天茁壮生长。"},
{"word":"throat","ipa":"/θroʊt/","pos":"n.","cat":"cet4","meaning":"喉咙","example":"A sore throat.","exampleZh":"喉咙痛。"},
{"word":"tone","ipa":"/toʊn/","pos":"n.","cat":"cet4","meaning":"语气；音调","example":"A friendly tone.","exampleZh":"友好的语气。"},
{"word":"topic","ipa":"/ˈtɒpɪk/","pos":"n.","cat":"cet4","meaning":"话题","example":"A hot topic.","exampleZh":"热门话题。"},
{"word":"tough","ipa":"/tʌf/","pos":"adj.","cat":"cet4","meaning":"坚韧的；困难的","example":"A tough job.","exampleZh":"困难的工作。"},
{"word":"trace","ipa":"/treɪs/","pos":"v./n.","cat":"cet4","meaning":"追踪；痕迹","example":"Trace the source.","exampleZh":"追溯源头。"},
{"word":"tradition","ipa":"/trəˈdɪʃn/","pos":"n.","cat":"cet4","meaning":"传统","example":"Respect tradition.","exampleZh":"尊重传统。"},
{"word":"tragedy","ipa":"/ˈtrædʒədi/","pos":"n.","cat":"cet4","meaning":"悲剧","example":"A great tragedy.","exampleZh":"巨大的悲剧。"},
{"word":"trail","ipa":"/treɪl/","pos":"n./v.","cat":"cet4","meaning":"小径；追踪","example":"Hike the trail.","exampleZh":"走小径。"},
{"word":"transfer","ipa":"/trænsˈfɜːr/","pos":"v.","cat":"cet4","meaning":"转移；调动","example":"Transfer the money.","exampleZh":"转账。"},
{"word":"transform","ipa":"/trænsˈfɔːrm/","pos":"v.","cat":"cet4","meaning":"转变","example":"The city transformed.","exampleZh":"城市变了样。"},
{"word":"transit","ipa":"/ˈtrænzɪt/","pos":"n.","cat":"cet4","meaning":"运输； transit","example":"Public transit.","exampleZh":"公共交通。"},
{"word":"transmit","ipa":"/trænsˈmɪt/","pos":"v.","cat":"cet4","meaning":"传输；传播","example":"Transmit the signal.","exampleZh":"传输信号。"},
{"word":"transparent","ipa":"/trænsˈpærənt/","pos":"adj.","cat":"cet4","meaning":"透明的","example":"A transparent process.","exampleZh":"透明的过程。"},
{"word":"transport","ipa":"/trænsˈpɔːrt/","pos":"v./n.","cat":"cet4","meaning":"运输","example":"Transport goods.","exampleZh":"运输货物。"},
{"word":"trap","ipa":"/træp/","pos":"n./v.","cat":"cet4","meaning":"陷阱；困住","example":"Avoid the trap.","exampleZh":"避开陷阱。"},
{"word":"tremendous","ipa":"/trəˈmendəs/","pos":"adj.","cat":"cet4","meaning":"巨大的","example":"A tremendous effort.","exampleZh":"巨大的努力。"},
{"word":"trend","ipa":"/trend/","pos":"n.","cat":"cet4","meaning":"趋势","example":"A rising trend.","exampleZh":"上升的趋势。"},
{"word":"trial","ipa":"/ˈtraɪəl/","pos":"n.","cat":"cet4","meaning":"审判；试验","example":"A clinical trial.","exampleZh":"临床试验。"},
{"word":"tribe","ipa":"/traɪb/","pos":"n.","cat":"cet4","meaning":"部落","example":"A native tribe.","exampleZh":"土著部落。"},
{"word":"trick","ipa":"/trɪk/","pos":"n./v.","cat":"cet4","meaning":"诡计；戏弄","example":"A clever trick.","exampleZh":"聪明的把戏。"},
{"word":"trigger","ipa":"/ˈtrɪɡər/","pos":"v./n.","cat":"cet4","meaning":"触发；扳机","example":"The event triggered debate.","exampleZh":"事件引发了辩论。"},
{"word":"triumph","ipa":"/ˈtraɪəmf/","pos":"n./v.","cat":"cet4","meaning":"胜利","example":"A moment of triumph.","exampleZh":"胜利的时刻。"},
{"word":"troop","ipa":"/truːp/","pos":"n.","cat":"cet4","meaning":"军队；一群","example":"Troops marched.","exampleZh":"军队行进了。"},
{"word":"tropical","ipa":"/ˈtrɒpɪkl/","pos":"adj.","cat":"cet4","meaning":"热带的","example":"Tropical climate.","exampleZh":"热带气候。"},
{"word":"truly","ipa":"/ˈtruːli/","pos":"adv.","cat":"cet4","meaning":"真正地","example":"I am truly sorry.","exampleZh":"我真的很抱歉。"},
{"word":"trust","ipa":"/trʌst/","pos":"n./v.","cat":"cet4","meaning":"信任","example":"Build trust.","exampleZh":"建立信任。"},
{"word":"tube","ipa":"/tjuːb/","pos":"n.","cat":"cet4","meaning":"管子","example":"A test tube.","exampleZh":"试管。"},
{"word":"tune","ipa":"/tjuːn/","pos":"n./v.","cat":"cet4","meaning":"曲调；调音","example":"Sing a tune.","exampleZh":"唱支曲子。"},
{"word":"turbine","ipa":"/ˈtɜːrbaɪn/","pos":"n.","cat":"cet4","meaning":"涡轮机","example":"A wind turbine.","exampleZh":"风力涡轮机。"},
{"word":"turnover","ipa":"/ˈtɜːrnoʊvər/","pos":"n.","cat":"cet4","meaning":"营业额；流动","example":"Staff turnover.","exampleZh":"员工流动率。"},
{"word":"twist","ipa":"/twɪst/","pos":"v./n.","cat":"cet4","meaning":"扭曲；转弯","example":"Twist the wire.","exampleZh":"拧铁丝。"},
{"word":"ultimate","ipa":"/ˈʌltɪmət/","pos":"adj.","cat":"cet4","meaning":"最终的","example":"The ultimate goal.","exampleZh":"最终目标。"},
{"word":"uncover","ipa":"/ʌnˈkʌvər/","pos":"v.","cat":"cet4","meaning":"揭露","example":"Uncover the truth.","exampleZh":"揭露真相。"},
{"word":"undergo","ipa":"/ˌʌndərˈɡoʊ/","pos":"v.","cat":"cet4","meaning":"经历；经受","example":"Undergo treatment.","exampleZh":"接受治疗。"},
{"word":"undertake","ipa":"/ˌʌndərˈteɪk/","pos":"v.","cat":"cet4","meaning":"承担；从事","example":"Undertake a task.","exampleZh":"承担任务。"},
{"word":"uneasy","ipa":"/ʌnˈiːzi/","pos":"adj.","cat":"cet4","meaning":"不安的","example":"He felt uneasy.","exampleZh":"他感到不安。"},
{"word":"unexpected","ipa":"/ˌʌnɪkˈspektɪd/","pos":"adj.","cat":"cet4","meaning":"意外的","example":"An unexpected guest.","exampleZh":"不速之客。"},
{"word":"unique","ipa":"/juˈniːk/","pos":"adj.","cat":"cet4","meaning":"独特的","example":"A unique style.","exampleZh":"独特的风格。"},
{"word":"universal","ipa":"/ˌjuːnɪˈvɜːrsl/","pos":"adj.","cat":"cet4","meaning":"普遍的","example":"A universal truth.","exampleZh":"普遍真理。"},
{"word":"unlike","ipa":"/ʌnˈlaɪk/","pos":"prep.","cat":"cet4","meaning":"不像","example":"Unlike his brother, he is calm.","exampleZh":"与他兄弟不同，他很冷静。"},
{"word":"update","ipa":"/ˌʌpˈdeɪt/","pos":"v./n.","cat":"cet4","meaning":"更新","example":"Update the app.","exampleZh":"更新应用。"},
{"word":"upgrade","ipa":"/ˌʌpˈɡreɪd/","pos":"v.","cat":"cet4","meaning":"升级","example":"Upgrade the system.","exampleZh":"升级系统。"},
{"word":"uphold","ipa":"/ʌpˈhoʊld/","pos":"v.","cat":"cet4","meaning":"维护；支持","example":"Uphold the law.","exampleZh":"维护法律。"},
{"word":"upset","ipa":"/ʌpˈset/","pos":"v./adj.","cat":"cet4","meaning":"使心烦；心烦的","example":"The news upset her.","exampleZh":"消息让她心烦。"},
{"word":"urban","ipa":"/ˈɜːrbən/","pos":"adj.","cat":"cet4","meaning":"城市的","example":"Urban life.","exampleZh":"城市生活。"},
{"word":"urge","ipa":"/ɜːrdʒ/","pos":"v./n.","cat":"cet4","meaning":"催促；强烈愿望","example":"I urge you to go.","exampleZh":"我催你去。"},
{"word":"utility","ipa":"/juːˈtɪləti/","pos":"n.","cat":"cet4","meaning":"效用；公用事业","example":"Public utility.","exampleZh":"公共事业。"},
{"word":"utmost","ipa":"/ˈʌtmoʊst/","pos":"adj./n.","cat":"cet4","meaning":"极度的；极限","example":"Do your utmost.","exampleZh":"尽你最大努力。"},
{"word":"vacant","ipa":"/ˈveɪkənt/","pos":"adj.","cat":"cet4","meaning":"空的；空缺的","example":"A vacant post.","exampleZh":"空缺职位。"},
{"word":"vague","ipa":"/veɪɡ/","pos":"adj.","cat":"cet4","meaning":"模糊的","example":"A vague answer.","exampleZh":"含糊的回答。"},
{"word":"valid","ipa":"/ˈvælɪd/","pos":"adj.","cat":"cet4","meaning":"有效的","example":"A valid ticket.","exampleZh":"有效票。"},
{"word":"vanish","ipa":"/ˈvænɪʃ/","pos":"v.","cat":"cet4","meaning":"消失","example":"The mist vanished.","exampleZh":"雾散了。"},
{"word":"variable","ipa":"/ˈveriəbl/","pos":"adj./n.","cat":"cet4","meaning":"可变的；变量","example":"A variable rate.","exampleZh":"浮动利率。"},
{"word":"variation","ipa":"/ˌveriˈeɪʃn/","pos":"n.","cat":"cet4","meaning":"变化；变体","example":"A slight variation.","exampleZh":"微小的变化。"},
{"word":"variety","ipa":"/vəˈraɪəti/","pos":"n.","cat":"cet4","meaning":"多样；种类","example":"A variety of goods.","exampleZh":"各种各样的商品。"},
{"word":"various","ipa":"/ˈveriəs/","pos":"adj.","cat":"cet4","meaning":"各种各样的","example":"Various options.","exampleZh":"各种选项。"},
{"word":"vast","ipa":"/væst/","pos":"adj.","cat":"cet4","meaning":"广阔的","example":"A vast desert.","exampleZh":"广阔的沙漠。"},
{"word":"vehicle","ipa":"/ˈviːəkl/","pos":"n.","cat":"cet4","meaning":"车辆；媒介","example":"A green vehicle.","exampleZh":"新能源车。"},
{"word":"venture","ipa":"/ˈventʃər/","pos":"n./v.","cat":"cet4","meaning":"冒险；企业","example":"A joint venture.","exampleZh":"合资企业。"},
{"word":"version","ipa":"/ˈvɜːrʒn/","pos":"n.","cat":"cet4","meaning":"版本","example":"The latest version.","exampleZh":"最新版本。"},
{"word":"veteran","ipa":"/ˈvetərən/","pos":"n./adj.","cat":"cet4","meaning":"老兵；经验丰富的","example":"A veteran teacher.","exampleZh":"资深教师。"},
{"word":"via","ipa":"/ˈvaɪə/","pos":"prep.","cat":"cet4","meaning":"经由","example":"Send it via email.","exampleZh":"用邮件发。"},
{"word":"victim","ipa":"/ˈvɪktɪm/","pos":"n.","cat":"cet4","meaning":"受害者","example":"A flood victim.","exampleZh":"洪灾受害者。"},
{"word":"viewpoint","ipa":"/ˈvjuːpɔɪnt/","pos":"n.","cat":"cet4","meaning":"观点","example":"From my viewpoint.","exampleZh":"依我看。"},
{"word":"violate","ipa":"/ˈvaɪəleɪt/","pos":"v.","cat":"cet4","meaning":"违反；侵犯","example":"Violate the rule.","exampleZh":"违反规定。"},
{"word":"virtual","ipa":"/ˈvɜːrtʃuəl/","pos":"adj.","cat":"cet4","meaning":"虚拟的","example":"A virtual meeting.","exampleZh":"虚拟会议。"},
{"word":"visible","ipa":"/ˈvɪzəbl/","pos":"adj.","cat":"cet4","meaning":"可见的","example":"The stars are visible.","exampleZh":"星星可见。"},
{"word":"vision","ipa":"/ˈvɪʒn/","pos":"n.","cat":"cet4","meaning":"视力；愿景","example":"A clear vision.","exampleZh":"清晰的愿景。"},
{"word":"vital","ipa":"/ˈvaɪtl/","pos":"adj.","cat":"cet4","meaning":"至关重要的","example":"Sleep is vital.","exampleZh":"睡眠至关重要。"},
{"word":"vivid","ipa":"/ˈvɪvɪd/","pos":"adj.","cat":"cet4","meaning":"生动的","example":"A vivid memory.","exampleZh":"生动的记忆。"},
{"word":"voluntary","ipa":"/ˈvɒləntri/","pos":"adj.","cat":"cet4","meaning":"自愿的","example":"Voluntary work.","exampleZh":"志愿工作。"},
{"word":"volunteer","ipa":"/ˌvɒlənˈtɪr/","pos":"n./v.","cat":"cet4","meaning":"志愿者；自愿","example":"He volunteered.","exampleZh":"他自愿参加了。"},
{"word":"vote","ipa":"/voʊt/","pos":"n./v.","cat":"cet4","meaning":"投票","example":"Cast your vote.","exampleZh":"投票。"},
{"word":"vulnerable","ipa":"/ˈvʌlnərəbl/","pos":"adj.","cat":"cet4","meaning":"脆弱的；易受伤害的","example":"The poor are vulnerable.","exampleZh":"穷人很脆弱。"},
{"word":"wage","ipa":"/weɪdʒ/","pos":"n.","cat":"cet4","meaning":"工资","example":"A daily wage.","exampleZh":"日薪。"},
{"word":"wander","ipa":"/ˈwɒndər/","pos":"v.","cat":"cet4","meaning":"漫步；走神","example":"He wandered in the park.","exampleZh":"他在公园漫步。"},
{"word":"wealth","ipa":"/welθ/","pos":"n.","cat":"cet4","meaning":"财富","example":"Health is wealth.","exampleZh":"健康即财富。"},
{"word":"weapon","ipa":"/ˈwepən/","pos":"n.","cat":"cet4","meaning":"武器","example":"A nuclear weapon.","exampleZh":"核武器。"},
{"word":"welfare","ipa":"/ˈwelfer/","pos":"n.","cat":"cet4","meaning":"福利","example":"Social welfare.","exampleZh":"社会福利。"},
{"word":"whereas","ipa":"/ˌwerˈæz/","pos":"conj.","cat":"cet4","meaning":"然而","example":"He is rich, whereas I am poor.","exampleZh":"他富有，而我贫穷。"},
{"word":"whilst","ipa":"/waɪlst/","pos":"conj.","cat":"cet4","meaning":"当…时；虽然","example":"He read whilst eating.","exampleZh":"他边吃边读。"},
{"word":"widespread","ipa":"/ˈwaɪdspred/","pos":"adj.","cat":"cet4","meaning":"广泛的","example":"Widespread support.","exampleZh":"广泛支持。"},
{"word":"withdraw","ipa":"/wɪðˈdrɔː/","pos":"v.","cat":"cet4","meaning":"撤回；取款","example":"Withdraw money.","exampleZh":"取钱。"},
{"word":"withstand","ipa":"/wɪðˈstænd/","pos":"v.","cat":"cet4","meaning":"经受住","example":"Withstand the pressure.","exampleZh":"承受压力。"},
{"word":"witness","ipa":"/ˈwɪtnəs/","pos":"n./v.","cat":"cet4","meaning":"目击者；见证","example":"He witnessed the event.","exampleZh":"他目睹了事件。"},
{"word":"workforce","ipa":"/ˈwɜːrkfɔːrs/","pos":"n.","cat":"cet4","meaning":"劳动力","example":"A skilled workforce.","exampleZh":"技术劳动力。"},
{"word":"workshop","ipa":"/ˈwɜːrkʃɒp/","pos":"n.","cat":"cet4","meaning":"车间；研讨会","example":"A training workshop.","exampleZh":"培训研讨会。"},
{"word":"worldwide","ipa":"/ˈwɜːrldwaɪd/","pos":"adj./adv.","cat":"cet4","meaning":"全世界的","example":"A worldwide brand.","exampleZh":"全球品牌。"},
{"word":"worship","ipa":"/ˈwɜːrʃɪp/","pos":"v./n.","cat":"cet4","meaning":"崇拜；敬奉","example":"They worship nature.","exampleZh":"他们崇拜自然。"},
{"word":"worthwhile","ipa":"/ˈwɜːrθwaɪl/","pos":"adj.","cat":"cet4","meaning":"值得的","example":"A worthwhile cause.","exampleZh":"值得的事业。"},
{"word":"wound","ipa":"/wuːnd/","pos":"n./v.","cat":"cet4","meaning":"伤口；使受伤","example":"He wound his arm.","exampleZh":"他伤了手臂。"},
{"word":"yield","ipa":"/jiːld/","pos":"v./n.","cat":"cet4","meaning":"屈服；产量","example":"The field yielded crops.","exampleZh":"田地出产庄稼。"},
{"word":"youngster","ipa":"/ˈjʌŋstər/","pos":"n.","cat":"cet4","meaning":"年轻人","example":"The youngsters played.","exampleZh":"年轻人玩耍。"},
{"word":"zone","ipa":"/zoʊn/","pos":"n.","cat":"cet4","meaning":"区域","example":"A war zone.","exampleZh":"交战区。"}
];
