// 离线词库分片 3/5（由 split_offline_dict.js 生成，勿手改）
var OFFLINE_EXTRA_3 = [
{"word":"indeed","ipa":"/ɪnˈdiːd/","pos":"adv.","cat":"cet4","meaning":"确实；的确","example":"It is indeed true.","exampleZh":"这的确是真的。"},
{"word":"indicate","ipa":"/ˈɪndɪkeɪt/","pos":"v.","cat":"cet4","meaning":"表明；指示","example":"The data indicates growth.","exampleZh":"数据显示增长。"},
{"word":"indifferent","ipa":"/ɪnˈdɪfrənt/","pos":"adj.","cat":"cet4","meaning":"漠不关心的","example":"He was indifferent to fame.","exampleZh":"他对名利漠不关心。"},
{"word":"indispensable","ipa":"/ˌɪndɪˈspensəbl/","pos":"adj.","cat":"cet4","meaning":"不可或缺的","example":"Sleep is indispensable.","exampleZh":"睡眠不可或缺。"},
{"word":"individual","ipa":"/ˌɪndɪˈvɪdʒuəl/","pos":"adj./n.","cat":"cet4","meaning":"个人的；个人","example":"Respect each individual.","exampleZh":"尊重每个人。"},
{"word":"induce","ipa":"/ɪnˈdjuːs/","pos":"v.","cat":"cet4","meaning":"诱导；引起","example":"The drug induced sleep.","exampleZh":"药物引起了睡意。"},
{"word":"inevitable","ipa":"/ɪnˈevɪtəbl/","pos":"adj.","cat":"cet4","meaning":"不可避免的","example":"Change is inevitable.","exampleZh":"变化不可避免。"},
{"word":"infer","ipa":"/ɪnˈfɜːr/","pos":"v.","cat":"cet4","meaning":"推断","example":"We inferred the cause.","exampleZh":"我们推断出了原因。"},
{"word":"influence","ipa":"/ˈɪnfluəns/","pos":"n./v.","cat":"cet4","meaning":"影响","example":"Parents influence children.","exampleZh":"父母影响孩子。"},
{"word":"inform","ipa":"/ɪnˈfɔːrm/","pos":"v.","cat":"cet4","meaning":"通知","example":"Please inform me.","exampleZh":"请通知我。"},
{"word":"initial","ipa":"/ɪˈnɪʃl/","pos":"adj.","cat":"cet4","meaning":"最初的","example":"The initial step is key.","exampleZh":"第一步很关键。"},
{"word":"initiative","ipa":"/ɪˈnɪʃətɪv/","pos":"n.","cat":"cet4","meaning":"倡议；主动性","example":"He took the initiative.","exampleZh":"他主动牵头。"},
{"word":"injure","ipa":"/ˈɪndʒər/","pos":"v.","cat":"cet4","meaning":"伤害","example":"He injured his leg.","exampleZh":"他伤了腿。"},
{"word":"innocent","ipa":"/ˈɪnəsnt/","pos":"adj.","cat":"cet4","meaning":"无辜的；天真的","example":"He is innocent.","exampleZh":"他是无辜的。"},
{"word":"input","ipa":"/ˈɪnpʊt/","pos":"n./v.","cat":"cet4","meaning":"输入","example":"Your input is welcome.","exampleZh":"欢迎你的意见。"},
{"word":"inquiry","ipa":"/ɪnˈkwaɪəri/","pos":"n.","cat":"cet4","meaning":"询问；调查","example":"We made an inquiry.","exampleZh":"我们做了查询。"},
{"word":"insert","ipa":"/ɪnˈsɜːrt/","pos":"v.","cat":"cet4","meaning":"插入","example":"Insert the card.","exampleZh":"插入卡片。"},
{"word":"insight","ipa":"/ˈɪnsaɪt/","pos":"n.","cat":"cet4","meaning":"洞察；领悟","example":"The book gives insight.","exampleZh":"这本书给人启发。"},
{"word":"insist","ipa":"/ɪnˈsɪst/","pos":"v.","cat":"cet4","meaning":"坚持","example":"He insisted on paying.","exampleZh":"他坚持要付钱。"},
{"word":"inspect","ipa":"/ɪnˈspekt/","pos":"v.","cat":"cet4","meaning":"检查","example":"Inspect the goods.","exampleZh":"检查货物。"},
{"word":"inspire","ipa":"/ɪnˈspaɪər/","pos":"v.","cat":"cet4","meaning":"激励；启发","example":"The story inspired me.","exampleZh":"这个故事激励了我。"},
{"word":"install","ipa":"/ɪnˈstɔːl/","pos":"v.","cat":"cet4","meaning":"安装","example":"We installed the software.","exampleZh":"我们装了软件。"},
{"word":"instance","ipa":"/ˈɪnstəns/","pos":"n.","cat":"cet4","meaning":"实例；情况","example":"For instance, try again.","exampleZh":"比如，再试一次。"},
{"word":"instant","ipa":"/ˈɪnstənt/","pos":"adj./n.","cat":"cet4","meaning":"立刻的；瞬间","example":"I need an instant reply.","exampleZh":"我需要立刻回复。"},
{"word":"instinct","ipa":"/ˈɪnstɪŋkt/","pos":"n.","cat":"cet4","meaning":"本能","example":"Survival is instinct.","exampleZh":"求生是本能。"},
{"word":"institute","ipa":"/ˈɪnstɪtjuːt/","pos":"n.","cat":"cet4","meaning":"机构；学院","example":"A research institute.","exampleZh":"一家研究机构。"},
{"word":"instruct","ipa":"/ɪnˈstrʌkt/","pos":"v.","cat":"cet4","meaning":"指导；指示","example":"He instructed the team.","exampleZh":"他指导了团队。"},
{"word":"instrument","ipa":"/ˈɪnstrumənt/","pos":"n.","cat":"cet4","meaning":"仪器；乐器","example":"The instrument is precise.","exampleZh":"仪器很精密。"},
{"word":"insult","ipa":"/ɪnˈsʌlt/","pos":"v./n.","cat":"cet4","meaning":"侮辱","example":"His words insulted her.","exampleZh":"他的话侮辱了她。"},
{"word":"insure","ipa":"/ɪnˈʃʊr/","pos":"v.","cat":"cet4","meaning":"给…保险","example":"Insure the cargo.","exampleZh":"给货物投保。"},
{"word":"integrate","ipa":"/ˈɪntɪɡreɪt/","pos":"v.","cat":"cet4","meaning":"整合；使融入","example":"Integrate the systems.","exampleZh":"整合系统。"},
{"word":"integrity","ipa":"/ɪnˈteɡrəti/","pos":"n.","cat":"cet4","meaning":"诚实；完整","example":"He is a man of integrity.","exampleZh":"他是个正直的人。"},
{"word":"intellectual","ipa":"/ˌɪntəˈlektʃuəl/","pos":"adj./n.","cat":"cet4","meaning":"智力的；知识分子","example":"An intellectual debate.","exampleZh":"一场理智的辩论。"},
{"word":"intend","ipa":"/ɪnˈtend/","pos":"v.","cat":"cet4","meaning":"打算","example":"I intend to leave.","exampleZh":"我打算离开。"},
{"word":"intense","ipa":"/ɪnˈtens/","pos":"adj.","cat":"cet4","meaning":"强烈的；剧烈的","example":"The pain was intense.","exampleZh":"疼痛剧烈。"},
{"word":"interact","ipa":"/ˌɪntərˈækt/","pos":"v.","cat":"cet4","meaning":"互动","example":"Users interact with the app.","exampleZh":"用户与app互动。"},
{"word":"interest","ipa":"/ˈɪntrəst/","pos":"n./v.","cat":"cet4","meaning":"兴趣；利息","example":"He showed interest.","exampleZh":"他表现出兴趣。"},
{"word":"interfere","ipa":"/ˌɪntərˈfɪr/","pos":"v.","cat":"cet4","meaning":"干涉；干扰","example":"Do not interfere.","exampleZh":"不要干涉。"},
{"word":"internal","ipa":"/ɪnˈtɜːrnl/","pos":"adj.","cat":"cet4","meaning":"内部的","example":"Internal affairs.","exampleZh":"内部事务。"},
{"word":"interpret","ipa":"/ɪnˈtɜːrprɪt/","pos":"v.","cat":"cet4","meaning":"解释；口译","example":"Please interpret the law.","exampleZh":"请解释这条法律。"},
{"word":"interval","ipa":"/ˈɪntərvl/","pos":"n.","cat":"cet4","meaning":"间隔","example":"Trains run at short intervals.","exampleZh":"列车间隔很短。"},
{"word":"interview","ipa":"/ˈɪntərvjuː/","pos":"n./v.","cat":"cet4","meaning":"面试；采访","example":"She passed the interview.","exampleZh":"她通过了面试。"},
{"word":"intimate","ipa":"/ˈɪntɪmət/","pos":"adj.","cat":"cet4","meaning":"亲密的；私人的","example":"They are intimate friends.","exampleZh":"他们是密友。"},
{"word":"introduce","ipa":"/ˌɪntrəˈdjuːs/","pos":"v.","cat":"cet4","meaning":"介绍；引入","example":"He introduced a new method.","exampleZh":"他引入了一种新方法。"},
{"word":"invent","ipa":"/ɪnˈvent/","pos":"v.","cat":"cet4","meaning":"发明","example":"Who invented the light bulb?","exampleZh":"谁发明了电灯？"},
{"word":"invest","ipa":"/ɪnˈvest/","pos":"v.","cat":"cet4","meaning":"投资","example":"They invested in stocks.","exampleZh":"他们投资了股票。"},
{"word":"investigate","ipa":"/ɪnˈvestɪɡeɪt/","pos":"v.","cat":"cet4","meaning":"调查","example":"Police investigated.","exampleZh":"警方展开了调查。"},
{"word":"involve","ipa":"/ɪnˈvɒlv/","pos":"v.","cat":"cet4","meaning":"涉及；使参与","example":"The job involves travel.","exampleZh":"这工作要出差。"},
{"word":"isolate","ipa":"/ˈaɪsəleɪt/","pos":"v.","cat":"cet4","meaning":"孤立；隔离","example":"The patient was isolated.","exampleZh":"病人被隔离了。"},
{"word":"issue","ipa":"/ˈɪʃuː/","pos":"n./v.","cat":"cet4","meaning":"问题；发行","example":"We faced an issue.","exampleZh":"我们遇到了问题。"},
{"word":"joint","ipa":"/dʒɔɪnt/","pos":"adj./n.","cat":"cet4","meaning":"联合的；关节","example":"A joint statement.","exampleZh":"一份联合声明。"},
{"word":"justify","ipa":"/ˈdʒʌstɪfaɪ/","pos":"v.","cat":"cet4","meaning":"证明…正当","example":"He justified his choice.","exampleZh":"他证明了自己的选择合理。"},
{"word":"label","ipa":"/ˈleɪbl/","pos":"n./v.","cat":"cet4","meaning":"标签；贴标签","example":"Read the label.","exampleZh":"读一下标签。"},
{"word":"labor","ipa":"/ˈleɪbər/","pos":"n.","cat":"cet4","meaning":"劳动；劳工","example":"Labor day is near.","exampleZh":"劳动节快到了。"},
{"word":"launch","ipa":"/lɔːntʃ/","pos":"v./n.","cat":"cet4","meaning":"发射；发起","example":"They launched a product.","exampleZh":"他们发布了一款产品。"},
{"word":"leadership","ipa":"/ˈliːdərʃɪp/","pos":"n.","cat":"cet4","meaning":"领导力；领导层","example":"She showed leadership.","exampleZh":"她展现了领导力。"},
{"word":"leak","ipa":"/liːk/","pos":"v./n.","cat":"cet4","meaning":"泄漏","example":"The pipe leaked.","exampleZh":"管子漏水了。"},
{"word":"lean","ipa":"/liːn/","pos":"v./adj.","cat":"cet4","meaning":"倚靠；瘦的","example":"Lean against the wall.","exampleZh":"靠在墙上。"},
{"word":"leap","ipa":"/liːp/","pos":"v./n.","cat":"cet4","meaning":"跳跃；剧增","example":"A leap in sales.","exampleZh":"销量猛增。"},
{"word":"legal","ipa":"/ˈliːɡl/","pos":"adj.","cat":"cet4","meaning":"法律的；合法的","example":"Is it legal?","exampleZh":"这合法吗？"},
{"word":"legend","ipa":"/ˈledʒənd/","pos":"n.","cat":"cet4","meaning":"传说；图例","example":"The legend lives on.","exampleZh":"传说流传下来。"},
{"word":"legislation","ipa":"/ˌledʒɪsˈleɪʃn/","pos":"n.","cat":"cet4","meaning":"立法；法律","example":"New legislation passed.","exampleZh":"新法通过。"},
{"word":"liable","ipa":"/ˈlaɪəbl/","pos":"adj.","cat":"cet4","meaning":"有责任的；易…的","example":"He is liable for damage.","exampleZh":"他对损失负责。"},
{"word":"liberal","ipa":"/ˈlɪbərəl/","pos":"adj.","cat":"cet4","meaning":"自由的；开明的","example":"A liberal attitude.","exampleZh":"开明的态度。"},
{"word":"liberate","ipa":"/ˈlɪbəreɪt/","pos":"v.","cat":"cet4","meaning":"解放","example":"They liberated the city.","exampleZh":"他们解放了城市。"},
{"word":"license","ipa":"/ˈlaɪsns/","pos":"n.","cat":"cet4","meaning":"执照；许可","example":"Show your license.","exampleZh":"出示你的执照。"},
{"word":"limit","ipa":"/ˈlɪmɪt/","pos":"n./v.","cat":"cet4","meaning":"限制","example":"There is a time limit.","exampleZh":"有时间限制。"},
{"word":"link","ipa":"/lɪŋk/","pos":"n./v.","cat":"cet4","meaning":"链接；联系","example":"The two events are linked.","exampleZh":"两件事有关联。"},
{"word":"locate","ipa":"/loʊˈkeɪt/","pos":"v.","cat":"cet4","meaning":"位于；找出","example":"The hotel is located downtown.","exampleZh":"酒店位于市中心。"},
{"word":"logical","ipa":"/ˈlɒdʒɪkl/","pos":"adj.","cat":"cet4","meaning":"合乎逻辑的","example":"His argument is logical.","exampleZh":"他的论证合乎逻辑。"},
{"word":"loose","ipa":"/luːs/","pos":"adj.","cat":"cet4","meaning":"松的；宽松的","example":"The screw is loose.","exampleZh":"螺丝松了。"},
{"word":"loyal","ipa":"/ˈlɔɪəl/","pos":"adj.","cat":"cet4","meaning":"忠诚的","example":"A loyal friend.","exampleZh":"忠诚的朋友。"},
{"word":"luxury","ipa":"/ˈlʌkʃəri/","pos":"n.","cat":"cet4","meaning":"奢侈；奢侈品","example":"Travel is a luxury.","exampleZh":"旅行是一种奢侈。"},
{"word":"maintain","ipa":"/meɪnˈteɪn/","pos":"v.","cat":"cet4","meaning":"维持；保养","example":"Maintain the machine.","exampleZh":"保养机器。"},
{"word":"major","ipa":"/ˈmeɪdʒər/","pos":"adj./n.","cat":"cet4","meaning":"主要的；专业","example":"English is my major.","exampleZh":"英语是我的专业。"},
{"word":"manifest","ipa":"/ˈmænɪfest/","pos":"v./adj.","cat":"cet4","meaning":"显示；明显的","example":"The trend manifested.","exampleZh":"趋势显现了。"},
{"word":"manipulate","ipa":"/məˈnɪpjuleɪt/","pos":"v.","cat":"cet4","meaning":"操纵；操作","example":"Do not manipulate data.","exampleZh":"不要篡改数据。"},
{"word":"manner","ipa":"/ˈmænər/","pos":"n.","cat":"cet4","meaning":"方式；举止","example":"He spoke in a rude manner.","exampleZh":"他说话很粗鲁。"},
{"word":"manual","ipa":"/ˈmænjuəl/","pos":"adj./n.","cat":"cet4","meaning":"手工的；手册","example":"Read the manual.","exampleZh":"读一下手册。"},
{"word":"margin","ipa":"/ˈmɑːrdʒɪn/","pos":"n.","cat":"cet4","meaning":"页边；利润","example":"The margin is thin.","exampleZh":"利润很薄。"},
{"word":"massive","ipa":"/ˈmæsɪv/","pos":"adj.","cat":"cet4","meaning":"巨大的","example":"A massive building.","exampleZh":"一座巨大的建筑。"},
{"word":"mature","ipa":"/məˈtʃʊr/","pos":"adj.","cat":"cet4","meaning":"成熟的","example":"He is mature for his age.","exampleZh":"他比同龄人成熟。"},
{"word":"maximum","ipa":"/ˈmæksɪməm/","pos":"n./adj.","cat":"cet4","meaning":"最大值；最大的","example":"The maximum speed is 120.","exampleZh":"最高时速120。"},
{"word":"means","ipa":"/miːnz/","pos":"n.","cat":"cet4","meaning":"手段；方法","example":"This is a means to an end.","exampleZh":"这是达到目的的手段。"},
{"word":"measure","ipa":"/ˈmeʒər/","pos":"v./n.","cat":"cet4","meaning":"测量；措施","example":"Take measures now.","exampleZh":"现在就采取措施。"},
{"word":"media","ipa":"/ˈmiːdiə/","pos":"n.","cat":"cet4","meaning":"媒体","example":"The media reported it.","exampleZh":"媒体报道了此事。"},
{"word":"medium","ipa":"/ˈmiːdiəm/","pos":"n./adj.","cat":"cet4","meaning":"媒介；中等的","example":"English is a medium.","exampleZh":"英语是一种媒介。"},
{"word":"mental","ipa":"/ˈmentl/","pos":"adj.","cat":"cet4","meaning":"精神的；心理的","example":"Mental health matters.","exampleZh":"心理健康很重要。"},
{"word":"mere","ipa":"/mɪr/","pos":"adj.","cat":"cet4","meaning":"仅仅的","example":"A mere child.","exampleZh":"仅仅是个孩子。"},
{"word":"migrate","ipa":"/maɪˈɡreɪt/","pos":"v.","cat":"cet4","meaning":"迁移","example":"Birds migrate south.","exampleZh":"鸟儿南迁。"},
{"word":"minimum","ipa":"/ˈmɪnɪməm/","pos":"n./adj.","cat":"cet4","meaning":"最小值；最小的","example":"The minimum wage rose.","exampleZh":"最低工资提高了。"},
{"word":"minor","ipa":"/ˈmaɪnər/","pos":"adj./n.","cat":"cet4","meaning":"较小的；未成年人","example":"A minor error.","exampleZh":"一个小错误。"},
{"word":"minute","ipa":"/ˈmɪnɪt/","pos":"n.","cat":"cet4","meaning":"分钟；会议记录","example":"Wait a minute.","exampleZh":"等一下。"},
{"word":"miracle","ipa":"/ˈmɪrəkl/","pos":"n.","cat":"cet4","meaning":"奇迹","example":"It was a miracle.","exampleZh":"这是个奇迹。"},
{"word":"mirror","ipa":"/ˈmɪrər/","pos":"n./v.","cat":"cet4","meaning":"镜子；反映","example":"The lake mirrored the sky.","exampleZh":"湖面倒映着天空。"},
{"word":"mislead","ipa":"/ˌmɪsˈliːd/","pos":"v.","cat":"cet4","meaning":"误导","example":"Do not mislead others.","exampleZh":"不要误导别人。"},
{"word":"mission","ipa":"/ˈmɪʃn/","pos":"n.","cat":"cet4","meaning":"使命；任务","example":"Our mission is clear.","exampleZh":"我们的使命明确。"},
{"word":"mistake","ipa":"/mɪˈsteɪk/","pos":"n./v.","cat":"cet4","meaning":"错误；弄错","example":"Learn from mistakes.","exampleZh":"从错误中学习。"},
{"word":"mixture","ipa":"/ˈmɪkstʃər/","pos":"n.","cat":"cet4","meaning":"混合物","example":"A mixture of colors.","exampleZh":"颜色的混合。"},
{"word":"modify","ipa":"/ˈmɒdɪfaɪ/","pos":"v.","cat":"cet4","meaning":"修改","example":"We modified the plan.","exampleZh":"我们修改了计划。"},
{"word":"moist","ipa":"/mɔɪst/","pos":"adj.","cat":"cet4","meaning":"潮湿的","example":"The air is moist.","exampleZh":"空气潮湿。"},
{"word":"moral","ipa":"/ˈmɒrəl/","pos":"adj./n.","cat":"cet4","meaning":"道德的；寓意","example":"The moral of the story.","exampleZh":"故事的寓意。"},
{"word":"motivate","ipa":"/ˈmoʊtɪveɪt/","pos":"v.","cat":"cet4","meaning":"激励","example":"The prize motivated him.","exampleZh":"奖金激励了他。"},
{"word":"mutual","ipa":"/ˈmjuːtʃuəl/","pos":"adj.","cat":"cet4","meaning":"相互的","example":"Mutual respect.","exampleZh":"相互尊重。"},
{"word":"narrow","ipa":"/ˈnæroʊ/","pos":"adj.","cat":"cet4","meaning":"狭窄的","example":"A narrow road.","exampleZh":"一条窄路。"},
{"word":"navy","ipa":"/ˈneɪvi/","pos":"n.","cat":"cet4","meaning":"海军","example":"He joined the navy.","exampleZh":"他加入了海军。"},
{"word":"needless","ipa":"/ˈniːdləs/","pos":"adj.","cat":"cet4","meaning":"不必要的","example":"Needless to say, be careful.","exampleZh":"不用说，要小心。"},
{"word":"negative","ipa":"/ˈneɡətɪv/","pos":"adj.","cat":"cet4","meaning":"负面的；否定的","example":"A negative answer.","exampleZh":"否定的回答。"},
{"word":"neglect","ipa":"/nɪˈɡlekt/","pos":"v./n.","cat":"cet4","meaning":"忽视","example":"Do not neglect health.","exampleZh":"不要忽视健康。"},
{"word":"negotiate","ipa":"/nɪˈɡoʊʃieɪt/","pos":"v.","cat":"cet4","meaning":"谈判","example":"They negotiated a deal.","exampleZh":"他们谈成了一笔交易。"},
{"word":"neutral","ipa":"/ˈnjuːtrəl/","pos":"adj.","cat":"cet4","meaning":"中立的；中性的","example":"Stay neutral.","exampleZh":"保持中立。"},
{"word":"nevertheless","ipa":"/ˌnevərðəˈles/","pos":"adv.","cat":"cet4","meaning":"然而；尽管如此","example":"It is hard; nevertheless we try.","exampleZh":"这很难，但我们仍尝试。"},
{"word":"nightmare","ipa":"/ˈnaɪtmer/","pos":"n.","cat":"cet4","meaning":"噩梦","example":"It was a nightmare.","exampleZh":"那是一场噩梦。"},
{"word":"noble","ipa":"/ˈnoʊbl/","pos":"adj.","cat":"cet4","meaning":"高尚的；贵族的","example":"A noble cause.","exampleZh":"高尚的事业。"},
{"word":"noticeable","ipa":"/ˈnoʊtɪsəbl/","pos":"adj.","cat":"cet4","meaning":"明显的","example":"A noticeable change.","exampleZh":"明显的变化。"},
{"word":"notion","ipa":"/ˈnoʊʃn/","pos":"n.","cat":"cet4","meaning":"概念；想法","example":"He has odd notions.","exampleZh":"他有些奇怪的想法。"},
{"word":"nowhere","ipa":"/ˈnoʊwer/","pos":"adv.","cat":"cet4","meaning":"无处","example":"The key is nowhere.","exampleZh":"钥匙不知去向。"},
{"word":"nuclear","ipa":"/ˈnuːkliər/","pos":"adj.","cat":"cet4","meaning":"核能的；核心的","example":"Nuclear energy.","exampleZh":"核能。"},
{"word":"obey","ipa":"/əˈbeɪ/","pos":"v.","cat":"cet4","meaning":"服从","example":"Obey the rules.","exampleZh":"遵守规则。"},
{"word":"object","ipa":"/ˈɒbdʒɪkt/","pos":"n./v.","cat":"cet4","meaning":"物体；反对","example":"I object to this plan.","exampleZh":"我反对这个计划。"},
{"word":"objective","ipa":"/əbˈdʒektɪv/","pos":"adj./n.","cat":"cet4","meaning":"客观的；目标","example":"An objective view.","exampleZh":"客观的看法。"},
{"word":"oblige","ipa":"/əˈblaɪdʒ/","pos":"v.","cat":"cet4","meaning":"迫使；帮忙","example":"I am obliged to go.","exampleZh":"我不得不去。"},
{"word":"observe","ipa":"/əbˈzɜːrv/","pos":"v.","cat":"cet4","meaning":"观察；遵守","example":"Observe the stars.","exampleZh":"观察星星。"},
{"word":"obstacle","ipa":"/ˈɒbstəkl/","pos":"n.","cat":"cet4","meaning":"障碍","example":"Poverty is an obstacle.","exampleZh":"贫穷是障碍。"},
{"word":"obtain","ipa":"/əbˈteɪn/","pos":"v.","cat":"cet4","meaning":"获得","example":"He obtained a degree.","exampleZh":"他拿到了学位。"},
{"word":"obvious","ipa":"/ˈɒbviəs/","pos":"adj.","cat":"cet4","meaning":"明显的","example":"The answer is obvious.","exampleZh":"答案很明显。"},
{"word":"occasion","ipa":"/əˈkeɪʒn/","pos":"n.","cat":"cet4","meaning":"场合；时机","example":"A special occasion.","exampleZh":"特殊场合。"},
{"word":"occupy","ipa":"/ˈɒkjupaɪ/","pos":"v.","cat":"cet4","meaning":"占据；使忙碌","example":"The army occupied the city.","exampleZh":"军队占领了城市。"},
{"word":"occur","ipa":"/əˈkɜːr/","pos":"v.","cat":"cet4","meaning":"发生；想到","example":"An accident occurred.","exampleZh":"发生了一起事故。"},
{"word":"offend","ipa":"/əˈfend/","pos":"v.","cat":"cet4","meaning":"冒犯","example":"I hope I didn't offend.","exampleZh":"希望我没冒犯你。"},
{"word":"offset","ipa":"/ˈɔːfset/","pos":"v.","cat":"cet4","meaning":"抵消","example":"The gain offsets the loss.","exampleZh":"收益抵消了损失。"},
{"word":"offspring","ipa":"/ˈɔːfsprɪŋ/","pos":"n.","cat":"cet4","meaning":"后代；子女","example":"They have no offspring.","exampleZh":"他们没有子女。"},
{"word":"online","ipa":"/ˌɒnˈlaɪn/","pos":"adj./adv.","cat":"cet4","meaning":"在线的","example":"Shop online.","exampleZh":"网上购物。"},
{"word":"opponent","ipa":"/əˈpoʊnənt/","pos":"n.","cat":"cet4","meaning":"对手","example":"A tough opponent.","exampleZh":"强劲的对手。"},
{"word":"opportunity","ipa":"/ˌɒpəˈtjuːnəti/","pos":"n.","cat":"cet4","meaning":"机会","example":"Seize the opportunity.","exampleZh":"抓住机会。"},
{"word":"oppose","ipa":"/əˈpoʊz/","pos":"v.","cat":"cet4","meaning":"反对","example":"They opposed the law.","exampleZh":"他们反对这项法律。"},
{"word":"optical","ipa":"/ˈɒptɪkl/","pos":"adj.","cat":"cet4","meaning":"光学的；视觉的","example":"An optical illusion.","exampleZh":"视觉错觉。"},
{"word":"optimistic","ipa":"/ˌɒptɪˈmɪstɪk/","pos":"adj.","cat":"cet4","meaning":"乐观的","example":"He is optimistic.","exampleZh":"他很乐观。"},
{"word":"option","ipa":"/ˈɒpʃn/","pos":"n.","cat":"cet4","meaning":"选择","example":"We have two options.","exampleZh":"我们有两个选择。"},
{"word":"organic","ipa":"/ɔːrˈɡænɪk/","pos":"adj.","cat":"cet4","meaning":"有机的；器官的","example":"Organic food.","exampleZh":"有机食品。"},
{"word":"organize","ipa":"/ˈɔːrɡənaɪz/","pos":"v.","cat":"cet4","meaning":"组织","example":"She organized the event.","exampleZh":"她组织了活动。"},
{"word":"origin","ipa":"/ˈɒrɪdʒɪn/","pos":"n.","cat":"cet4","meaning":"起源；出身","example":"The origin of the river.","exampleZh":"这条河的源头。"},
{"word":"outcome","ipa":"/ˈaʊtkʌm/","pos":"n.","cat":"cet4","meaning":"结果","example":"The outcome is unclear.","exampleZh":"结果不明。"},
{"word":"outlet","ipa":"/ˈaʊtlet/","pos":"n.","cat":"cet4","meaning":"出口； outlet","example":"A retail outlet.","exampleZh":"一家零售店。"},
{"word":"outline","ipa":"/ˈaʊtlaɪn/","pos":"n./v.","cat":"cet4","meaning":"大纲；概述","example":"Give an outline.","exampleZh":"给个大纲。"},
{"word":"outlook","ipa":"/ˈaʊtlʊk/","pos":"n.","cat":"cet4","meaning":"展望；看法","example":"The economic outlook.","exampleZh":"经济前景。"},
{"word":"output","ipa":"/ˈaʊtpʊt/","pos":"n.","cat":"cet4","meaning":"产量；输出","example":"Factory output rose.","exampleZh":"工厂产量上升。"},
{"word":"outstanding","ipa":"/aʊtˈstændɪŋ/","pos":"adj.","cat":"cet4","meaning":"杰出的；未解决的","example":"An outstanding student.","exampleZh":"一名杰出的学生。"},
{"word":"overall","ipa":"/ˌoʊvərˈɔːl/","pos":"adj./adv.","cat":"cet4","meaning":"总体的","example":"Overall, it is good.","exampleZh":"总体不错。"},
{"word":"overcome","ipa":"/ˌoʊvərˈkʌm/","pos":"v.","cat":"cet4","meaning":"克服","example":"Overcome the fear.","exampleZh":"克服恐惧。"},
{"word":"overhead","ipa":"/ˌoʊvərˈhed/","pos":"adj./adv.","cat":"cet4","meaning":"在头顶的； overhead","example":"Overhead costs.","exampleZh":"管理费用。"},
{"word":"overlook","ipa":"/ˌoʊvərˈlʊk/","pos":"v.","cat":"cet4","meaning":"忽视；俯瞰","example":"Do not overlook details.","exampleZh":"不要忽视细节。"},
{"word":"owe","ipa":"/oʊ/","pos":"v.","cat":"cet4","meaning":"欠；归功于","example":"I owe you thanks.","exampleZh":"我得感谢你。"},
{"word":"owner","ipa":"/ˈoʊnər/","pos":"n.","cat":"cet4","meaning":"所有者","example":"The owner agreed.","exampleZh":"所有者同意了。"},
{"word":"pace","ipa":"/peɪs/","pos":"n./v.","cat":"cet4","meaning":"步伐；踱步","example":"Slow your pace.","exampleZh":"放慢脚步。"},
{"word":"pack","ipa":"/pæk/","pos":"v./n.","cat":"cet4","meaning":"打包；包","example":"Pack your bag.","exampleZh":"收拾行李。"},
{"word":"partial","ipa":"/ˈpɑːrʃl/","pos":"adj.","cat":"cet4","meaning":"部分的；偏袒的","example":"A partial success.","exampleZh":"部分成功。"},
{"word":"participate","ipa":"/pɑːrˈtɪsɪpeɪt/","pos":"v.","cat":"cet4","meaning":"参与","example":"Participate in the game.","exampleZh":"参与游戏。"},
{"word":"particular","ipa":"/pərˈtɪkjələr/","pos":"adj.","cat":"cet4","meaning":"特别的；特定的","example":"In particular, note this.","exampleZh":"尤其注意这点。"},
{"word":"passion","ipa":"/ˈpæʃn/","pos":"n.","cat":"cet4","meaning":"热情","example":"She has a passion for art.","exampleZh":"她热爱艺术。"},
{"word":"passive","ipa":"/ˈpæsɪv/","pos":"adj.","cat":"cet4","meaning":"被动的","example":"A passive role.","exampleZh":"被动的角色。"},
{"word":"patience","ipa":"/ˈpeɪʃns/","pos":"n.","cat":"cet4","meaning":"耐心","example":"He has patience.","exampleZh":"他很有耐心。"},
{"word":"peak","ipa":"/piːk/","pos":"n./v.","cat":"cet4","meaning":"山峰；顶峰","example":"Sales peaked in June.","exampleZh":"销量在六月达峰。"},
{"word":"peer","ipa":"/pɪr/","pos":"n.","cat":"cet4","meaning":"同龄人；同行","example":"He faced his peers.","exampleZh":"他面对同龄人。"},
{"word":"perceive","ipa":"/pərˈsiːv/","pos":"v.","cat":"cet4","meaning":"察觉；理解","example":"We perceive a change.","exampleZh":"我们察觉到了变化。"},
{"word":"perform","ipa":"/pərˈfɔːrm/","pos":"v.","cat":"cet4","meaning":"执行；表演","example":"The team performed well.","exampleZh":"团队表现出色。"},
{"word":"permanent","ipa":"/ˈpɜːrmənənt/","pos":"adj.","cat":"cet4","meaning":"永久的","example":"A permanent job.","exampleZh":"一份固定工作。"},
{"word":"permission","ipa":"/pərˈmɪʃn/","pos":"n.","cat":"cet4","meaning":"许可","example":"Ask for permission.","exampleZh":"请求许可。"},
{"word":"persist","ipa":"/pərˈsɪst/","pos":"v.","cat":"cet4","meaning":"坚持","example":"Persist in your effort.","exampleZh":"坚持努力。"},
{"word":"personal","ipa":"/ˈpɜːrsənl/","pos":"adj.","cat":"cet4","meaning":"个人的","example":"A personal matter.","exampleZh":"私事。"},
{"word":"persuade","ipa":"/pərˈsweɪd/","pos":"v.","cat":"cet4","meaning":"说服","example":"He persuaded me.","exampleZh":"他说服了我。"},
{"word":"pessimistic","ipa":"/ˌpesɪˈmɪstɪk/","pos":"adj.","cat":"cet4","meaning":"悲观的","example":"Don't be pessimistic.","exampleZh":"别悲观。"},
{"word":"phase","ipa":"/feɪz/","pos":"n.","cat":"cet4","meaning":"阶段","example":"The project has phases.","exampleZh":"项目分阶段。"},
{"word":"phenomenon","ipa":"/fəˈnɒmɪnən/","pos":"n.","cat":"cet4","meaning":"现象","example":"A natural phenomenon.","exampleZh":"自然现象。"},
{"word":"physical","ipa":"/ˈfɪzɪkl/","pos":"adj.","cat":"cet4","meaning":"身体的；物理的","example":"Physical exercise.","exampleZh":"体育锻炼。"},
{"word":"policy","ipa":"/ˈpɒləsi/","pos":"n.","cat":"cet4","meaning":"政策；保险单","example":"The new policy.","exampleZh":"新政策。"},
{"word":"political","ipa":"/pəˈlɪtɪkl/","pos":"adj.","cat":"cet4","meaning":"政治的","example":"A political debate.","exampleZh":"政治辩论。"}
];
