// 离线词库分片 4/5（由 split_offline_dict.js 生成，勿手改）
var OFFLINE_EXTRA_4 = [
{"word":"portion","ipa":"/ˈpɔːrʃn/","pos":"n.","cat":"cet4","meaning":"部分；一份","example":"A portion of the food.","exampleZh":"一份食物。"},
{"word":"pose","ipa":"/poʊz/","pos":"v.","cat":"cet4","meaning":"造成；摆姿势","example":"It poses a risk.","exampleZh":"这带来了风险。"},
{"word":"positive","ipa":"/ˈpɒzətɪv/","pos":"adj.","cat":"cet4","meaning":"积极的；阳性的","example":"A positive attitude.","exampleZh":"积极的态度。"},
{"word":"possess","ipa":"/pəˈzes/","pos":"v.","cat":"cet4","meaning":"拥有","example":"He possesses talent.","exampleZh":"他拥有才华。"},
{"word":"postpone","ipa":"/poʊˈspoʊn/","pos":"v.","cat":"cet4","meaning":"推迟","example":"They postponed the meeting.","exampleZh":"他们推迟了会议。"},
{"word":"potential","ipa":"/pəˈtenʃl/","pos":"adj./n.","cat":"cet4","meaning":"潜在的；潜力","example":"A potential market.","exampleZh":"潜在市场。"},
{"word":"poverty","ipa":"/ˈpɒvərti/","pos":"n.","cat":"cet4","meaning":"贫困","example":"Fight poverty.","exampleZh":"消除贫困。"},
{"word":"precise","ipa":"/prɪˈsaɪs/","pos":"adj.","cat":"cet4","meaning":"精确的","example":"Be precise.","exampleZh":"要精确。"},
{"word":"predict","ipa":"/prɪˈdɪkt/","pos":"v.","cat":"cet4","meaning":"预测","example":"Predict the weather.","exampleZh":"预测天气。"},
{"word":"prefer","ipa":"/prɪˈfɜːr/","pos":"v.","cat":"cet4","meaning":"更喜欢","example":"I prefer tea.","exampleZh":"我更喜欢茶。"},
{"word":"pregnant","ipa":"/ˈpreɡnənt/","pos":"adj.","cat":"cet4","meaning":"怀孕的","example":"She is pregnant.","exampleZh":"她怀孕了。"},
{"word":"prejudice","ipa":"/ˈpredʒudɪs/","pos":"n.","cat":"cet4","meaning":"偏见","example":"Overcome prejudice.","exampleZh":"克服偏见。"},
{"word":"preliminary","ipa":"/prɪˈlɪmɪneri/","pos":"adj.","cat":"cet4","meaning":"初步的","example":"A preliminary study.","exampleZh":"初步研究。"},
{"word":"prescribe","ipa":"/prɪˈskraɪb/","pos":"v.","cat":"cet4","meaning":"开处方；规定","example":"The doctor prescribed medicine.","exampleZh":"医生开了药。"},
{"word":"present","ipa":"/ˈpreznt/","pos":"adj./v./n.","cat":"cet4","meaning":"现在的；呈现；礼物","example":"Present your idea.","exampleZh":"展示你的想法。"},
{"word":"preserve","ipa":"/prɪˈzɜːrv/","pos":"v.","cat":"cet4","meaning":"保护；保存","example":"Preserve the forest.","exampleZh":"保护森林。"},
{"word":"pressure","ipa":"/ˈpreʃər/","pos":"n.","cat":"cet4","meaning":"压力","example":"He works under pressure.","exampleZh":"他在压力下工作。"},
{"word":"presume","ipa":"/prɪˈzjuːm/","pos":"v.","cat":"cet4","meaning":"假定","example":"I presume you agree.","exampleZh":"我猜你同意。"},
{"word":"prevail","ipa":"/prɪˈveɪl/","pos":"v.","cat":"cet4","meaning":"盛行；获胜","example":"Justice will prevail.","exampleZh":"正义终将胜利。"},
{"word":"prevent","ipa":"/prɪˈvent/","pos":"v.","cat":"cet4","meaning":"防止","example":"Prevent the spread.","exampleZh":"防止扩散。"},
{"word":"primary","ipa":"/ˈpraɪmeri/","pos":"adj.","cat":"cet4","meaning":"主要的；初级的","example":"The primary goal.","exampleZh":"主要目标。"},
{"word":"primitive","ipa":"/ˈprɪmətɪv/","pos":"adj.","cat":"cet4","meaning":"原始的","example":"Primitive tools.","exampleZh":"原始工具。"},
{"word":"principal","ipa":"/ˈprɪnsəpl/","pos":"adj./n.","cat":"cet4","meaning":"主要的；校长","example":"The principal reason.","exampleZh":"主要原因。"},
{"word":"prior","ipa":"/ˈpraɪər/","pos":"adj.","cat":"cet4","meaning":"优先的；先前的","example":"Prior to the meeting.","exampleZh":"会议之前。"},
{"word":"priority","ipa":"/praɪˈɔːrəti/","pos":"n.","cat":"cet4","meaning":"优先；优先考虑的事","example":"Safety is the priority.","exampleZh":"安全是优先项。"},
{"word":"private","ipa":"/ˈpraɪvət/","pos":"adj.","cat":"cet4","meaning":"私人的","example":"A private conversation.","exampleZh":"私人谈话。"},
{"word":"probable","ipa":"/ˈprɒbəbl/","pos":"adj.","cat":"cet4","meaning":"可能的","example":"The probable cause.","exampleZh":"可能的原因。"},
{"word":"procedure","ipa":"/prəˈsiːdʒər/","pos":"n.","cat":"cet4","meaning":"程序；步骤","example":"Follow the procedure.","exampleZh":"按程序办。"},
{"word":"proceed","ipa":"/proʊˈsiːd/","pos":"v.","cat":"cet4","meaning":"继续进行","example":"Proceed with caution.","exampleZh":"谨慎进行。"},
{"word":"process","ipa":"/ˈprɒses/","pos":"n./v.","cat":"cet4","meaning":"过程；处理","example":"The application process.","exampleZh":"申请流程。"},
{"word":"proclaim","ipa":"/prəˈkleɪm/","pos":"v.","cat":"cet4","meaning":"宣布","example":"They proclaimed victory.","exampleZh":"他们宣布胜利。"},
{"word":"produce","ipa":"/prəˈdjuːs/","pos":"v.","cat":"cet4","meaning":"生产；产生","example":"The farm produces wheat.","exampleZh":"农场产小麦。"},
{"word":"profit","ipa":"/ˈprɒfɪt/","pos":"n./v.","cat":"cet4","meaning":"利润；获利","example":"The firm made a profit.","exampleZh":"公司盈利了。"},
{"word":"prohibit","ipa":"/prəˈhɪbɪt/","pos":"v.","cat":"cet4","meaning":"禁止","example":"Smoking is prohibited.","exampleZh":"禁止吸烟。"},
{"word":"prominent","ipa":"/ˈprɒmɪnənt/","pos":"adj.","cat":"cet4","meaning":"突出的；杰出的","example":"A prominent figure.","exampleZh":"一位杰出人物。"},
{"word":"promise","ipa":"/ˈprɒmɪs/","pos":"n./v.","cat":"cet4","meaning":"承诺","example":"He promised to help.","exampleZh":"他答应帮忙。"},
{"word":"promote","ipa":"/prəˈmoʊt/","pos":"v.","cat":"cet4","meaning":" promotion；促进","example":"They promoted the brand.","exampleZh":"他们推广了品牌。"},
{"word":"prompt","ipa":"/prɒmpt/","pos":"adj./v.","cat":"cet4","meaning":"迅速的；促使","example":"The prompt reply.","exampleZh":"迅速的回复。"},
{"word":"proper","ipa":"/ˈprɒpər/","pos":"adj.","cat":"cet4","meaning":"适当的","example":"Use proper tools.","exampleZh":"用合适的工具。"},
{"word":"propose","ipa":"/prəˈpoʊz/","pos":"v.","cat":"cet4","meaning":"提议；求婚","example":"He proposed a plan.","exampleZh":"他提出了一个计划。"},
{"word":"prospect","ipa":"/ˈprɒspekt/","pos":"n.","cat":"cet4","meaning":"前景；可能性","example":"The job has good prospects.","exampleZh":"这份工作前景不错。"},
{"word":"protect","ipa":"/prəˈtekt/","pos":"v.","cat":"cet4","meaning":"保护","example":"Protect the children.","exampleZh":"保护孩子。"},
{"word":"protein","ipa":"/ˈproʊtiːn/","pos":"n.","cat":"cet4","meaning":"蛋白质","example":"Eat more protein.","exampleZh":"多吃蛋白质。"},
{"word":"protest","ipa":"/ˈproʊtest/","pos":"n./v.","cat":"cet4","meaning":"抗议","example":"They protested the law.","exampleZh":"他们抗议这项法律。"},
{"word":"provide","ipa":"/prəˈvaɪd/","pos":"v.","cat":"cet4","meaning":"提供","example":"We provide service.","exampleZh":"我们提供服务。"},
{"word":"province","ipa":"/ˈprɒvɪns/","pos":"n.","cat":"cet4","meaning":"省","example":"He lives in the province.","exampleZh":"他住在省里。"},
{"word":"publish","ipa":"/ˈpʌblɪʃ/","pos":"v.","cat":"cet4","meaning":"出版；发布","example":"They published a book.","exampleZh":"他们出版了一本书。"},
{"word":"purpose","ipa":"/ˈpɜːrpəs/","pos":"n.","cat":"cet4","meaning":"目的","example":"What is the purpose?","exampleZh":"目的是什么？"},
{"word":"pursue","ipa":"/pərˈsuː/","pos":"v.","cat":"cet4","meaning":"追求；追赶","example":"Pursue your dream.","exampleZh":"追求梦想。"},
{"word":"qualify","ipa":"/ˈkwɒlɪfaɪ/","pos":"v.","cat":"cet4","meaning":"使合格；取得资格","example":"He qualified for the job.","exampleZh":"他胜任这份工作。"},
{"word":"quality","ipa":"/ˈkwɒləti/","pos":"n.","cat":"cet4","meaning":"质量；品质","example":"Focus on quality.","exampleZh":"注重质量。"},
{"word":"quantity","ipa":"/ˈkwɒntəti/","pos":"n.","cat":"cet4","meaning":"数量","example":"A large quantity.","exampleZh":"大量。"},
{"word":"quit","ipa":"/kwɪt/","pos":"v.","cat":"cet4","meaning":"放弃；辞职","example":"He quit smoking.","exampleZh":"他戒烟了。"},
{"word":"quote","ipa":"/kwoʊt/","pos":"v./n.","cat":"cet4","meaning":"引用；报价","example":"Quote the expert.","exampleZh":"引用专家的话。"},
{"word":"racial","ipa":"/ˈreɪʃl/","pos":"adj.","cat":"cet4","meaning":"种族的","example":"Racial equality.","exampleZh":"种族平等。"},
{"word":"radiation","ipa":"/ˌreɪdiˈeɪʃn/","pos":"n.","cat":"cet4","meaning":"辐射","example":"Limit radiation.","exampleZh":"限制辐射。"},
{"word":"radical","ipa":"/ˈrædɪkl/","pos":"adj.","cat":"cet4","meaning":"激进的；根本的","example":"A radical change.","exampleZh":"根本性的改变。"},
{"word":"rail","ipa":"/reɪl/","pos":"n.","cat":"cet4","meaning":"栏杆；铁路","example":"By rail.","exampleZh":"乘铁路。"},
{"word":"range","ipa":"/reɪndʒ/","pos":"n./v.","cat":"cet4","meaning":"范围；变动","example":"Prices range widely.","exampleZh":"价格差异很大。"},
{"word":"rank","ipa":"/ræŋk/","pos":"n./v.","cat":"cet4","meaning":"等级；排名","example":"He ranks first.","exampleZh":"他排第一。"},
{"word":"rare","ipa":"/rer/","pos":"adj.","cat":"cet4","meaning":"稀有的","example":"A rare book.","exampleZh":"珍本。"},
{"word":"rate","ipa":"/reɪt/","pos":"n./v.","cat":"cet4","meaning":"比率；评价","example":"The birth rate fell.","exampleZh":"出生率下降。"},
{"word":"rational","ipa":"/ˈræʃnəl/","pos":"adj.","cat":"cet4","meaning":"理性的","example":"A rational choice.","exampleZh":"理性的选择。"},
{"word":"react","ipa":"/riˈækt/","pos":"v.","cat":"cet4","meaning":"反应","example":"How did he react?","exampleZh":"他有何反应？"},
{"word":"realistic","ipa":"/ˌriːəˈlɪstɪk/","pos":"adj.","cat":"cet4","meaning":"现实的","example":"Set a realistic goal.","exampleZh":"定个现实的目标。"},
{"word":"rear","ipa":"/rɪr/","pos":"n./adj.","cat":"cet4","meaning":"后部；养育","example":"The rear door.","exampleZh":"后门。"},
{"word":"reasonable","ipa":"/ˈriːznəbl/","pos":"adj.","cat":"cet4","meaning":"合理的","example":"A reasonable price.","exampleZh":"合理的价格。"},
{"word":"recall","ipa":"/rɪˈkɔːl/","pos":"v.","cat":"cet4","meaning":"回忆；召回","example":"I recall the day.","exampleZh":"我记得那天。"},
{"word":"receipt","ipa":"/rɪˈsiːt/","pos":"n.","cat":"cet4","meaning":"收据","example":"Keep the receipt.","exampleZh":"保留收据。"},
{"word":"receive","ipa":"/rɪˈsiːv/","pos":"v.","cat":"cet4","meaning":"收到","example":"I received your letter.","exampleZh":"我收到了你的信。"},
{"word":"recession","ipa":"/rɪˈseʃn/","pos":"n.","cat":"cet4","meaning":"衰退","example":"The economy in recession.","exampleZh":"经济衰退。"},
{"word":"reckon","ipa":"/ˈrekən/","pos":"v.","cat":"cet4","meaning":"认为；估计","example":"I reckon he is right.","exampleZh":"我认为他是对的。"},
{"word":"recognition","ipa":"/ˌrekəɡˈnɪʃn/","pos":"n.","cat":"cet4","meaning":"认可；识别","example":"She won recognition.","exampleZh":"她获得了认可。"},
{"word":"recommend","ipa":"/ˌrekəˈmend/","pos":"v.","cat":"cet4","meaning":"推荐","example":"I recommend this book.","exampleZh":"我推荐这本书。"},
{"word":"recover","ipa":"/rɪˈkʌvər/","pos":"v.","cat":"cet4","meaning":"恢复","example":"He recovered quickly.","exampleZh":"他恢复得很快。"},
{"word":"reflect","ipa":"/rɪˈflekt/","pos":"v.","cat":"cet4","meaning":"反映；反思","example":"The book reflects life.","exampleZh":"书反映生活。"},
{"word":"reform","ipa":"/rɪˈfɔːrm/","pos":"n./v.","cat":"cet4","meaning":"改革","example":"Education reform.","exampleZh":"教育改革。"},
{"word":"refresh","ipa":"/rɪˈfreʃ/","pos":"v.","cat":"cet4","meaning":"使恢复；刷新","example":"Refresh the page.","exampleZh":"刷新页面。"},
{"word":"refugee","ipa":"/ˌrefjuˈdʒiː/","pos":"n.","cat":"cet4","meaning":"难民","example":"A refugee camp.","exampleZh":"难民营。"},
{"word":"refuse","ipa":"/rɪˈfjuːz/","pos":"v.","cat":"cet4","meaning":"拒绝","example":"She refused the gift.","exampleZh":"她拒绝了礼物。"},
{"word":"regard","ipa":"/rɪˈɡɑːrd/","pos":"v./n.","cat":"cet4","meaning":"认为；问候","example":"He is regarded as wise.","exampleZh":"他被认为很睿智。"},
{"word":"region","ipa":"/ˈriːdʒən/","pos":"n.","cat":"cet4","meaning":"地区","example":"The region is dry.","exampleZh":"该地区干旱。"},
{"word":"register","ipa":"/ˈredʒɪstər/","pos":"v.","cat":"cet4","meaning":"登记；注册","example":"Register online.","exampleZh":"在线注册。"},
{"word":"regulate","ipa":"/ˈreɡjuleɪt/","pos":"v.","cat":"cet4","meaning":"管理；调节","example":"The law regulates trade.","exampleZh":"法律监管贸易。"},
{"word":"reinforce","ipa":"/ˌriːɪnˈfɔːrs/","pos":"v.","cat":"cet4","meaning":"加强","example":"Reinforce the wall.","exampleZh":"加固墙体。"},
{"word":"reject","ipa":"/rɪˈdʒekt/","pos":"v.","cat":"cet4","meaning":"拒绝；驳回","example":"They rejected the plan.","exampleZh":"他们否决了计划。"},
{"word":"relate","ipa":"/rɪˈleɪt/","pos":"v.","cat":"cet4","meaning":"关联；叙述","example":"Relate to others.","exampleZh":"与他人建立联系。"},
{"word":"release","ipa":"/rɪˈliːs/","pos":"v./n.","cat":"cet4","meaning":"释放；发布","example":"They released a film.","exampleZh":"他们发布了一部电影。"},
{"word":"relevant","ipa":"/ˈreləvənt/","pos":"adj.","cat":"cet4","meaning":"相关的","example":"A relevant point.","exampleZh":"相关的观点。"},
{"word":"reliable","ipa":"/rɪˈlaɪəbl/","pos":"adj.","cat":"cet4","meaning":"可靠的","example":"A reliable friend.","exampleZh":"可靠的朋友。"},
{"word":"relief","ipa":"/rɪˈliːf/","pos":"n.","cat":"cet4","meaning":" relief；缓解","example":"The medicine brought relief.","exampleZh":"药物带来了缓解。"},
{"word":"religion","ipa":"/rɪˈlɪdʒən/","pos":"n.","cat":"cet4","meaning":"宗教","example":"Freedom of religion.","exampleZh":"宗教自由。"},
{"word":"rely","ipa":"/rɪˈlaɪ/","pos":"v.","cat":"cet4","meaning":"依赖","example":"Rely on yourself.","exampleZh":"靠自己。"},
{"word":"remain","ipa":"/rɪˈmeɪn/","pos":"v.","cat":"cet4","meaning":"保持；剩余","example":"Little remained.","exampleZh":"所剩无几。"},
{"word":"remark","ipa":"/rɪˈmɑːrk/","pos":"v./n.","cat":"cet4","meaning":"评论","example":"He remarked on the weather.","exampleZh":"他评论了天气。"},
{"word":"remarkable","ipa":"/rɪˈmɑːrkəbl/","pos":"adj.","cat":"cet4","meaning":"非凡的","example":"A remarkable achievement.","exampleZh":"非凡的成就。"},
{"word":"remedy","ipa":"/ˈremədi/","pos":"n./v.","cat":"cet4","meaning":" remedy；补救","example":"A legal remedy.","exampleZh":"法律补救。"},
{"word":"remote","ipa":"/rɪˈmoʊt/","pos":"adj.","cat":"cet4","meaning":"偏远的；远程的","example":"A remote village.","exampleZh":"偏远的村庄。"},
{"word":"remove","ipa":"/rɪˈmuːv/","pos":"v.","cat":"cet4","meaning":"移除","example":"Remove the stain.","exampleZh":"去除污渍。"},
{"word":"render","ipa":"/ˈrendər/","pos":"v.","cat":"cet4","meaning":"使得；提供","example":"The mistake rendered it useless.","exampleZh":"错误使它毫无用处。"},
{"word":"rent","ipa":"/rent/","pos":"n./v.","cat":"cet4","meaning":"租金；租","example":"Rent an apartment.","exampleZh":"租公寓。"},
{"word":"repair","ipa":"/rɪˈper/","pos":"v./n.","cat":"cet4","meaning":"修理","example":"Repair the car.","exampleZh":"修车。"},
{"word":"repeat","ipa":"/rɪˈpiːt/","pos":"v.","cat":"cet4","meaning":"重复","example":"Repeat after me.","exampleZh":"跟我读。"},
{"word":"replace","ipa":"/rɪˈpleɪs/","pos":"v.","cat":"cet4","meaning":"取代","example":"Replace the bulb.","exampleZh":"换灯泡。"},
{"word":"represent","ipa":"/ˌreprɪˈzent/","pos":"v.","cat":"cet4","meaning":"代表；象征","example":"He represents the firm.","exampleZh":"他代表公司。"},
{"word":"reputation","ipa":"/ˌrepjuˈteɪʃn/","pos":"n.","cat":"cet4","meaning":"声誉","example":"A good reputation.","exampleZh":"好声誉。"},
{"word":"request","ipa":"/rɪˈkwest/","pos":"n./v.","cat":"cet4","meaning":"请求","example":"We request your help.","exampleZh":"我们请求你的帮助。"},
{"word":"require","ipa":"/rɪˈkwaɪər/","pos":"v.","cat":"cet4","meaning":"需要","example":"The job requires skill.","exampleZh":"这工作需要技能。"},
{"word":"rescue","ipa":"/ˈreskjuː/","pos":"v./n.","cat":"cet4","meaning":"救援","example":"They rescued the cat.","exampleZh":"他们救了猫。"},
{"word":"resign","ipa":"/rɪˈzaɪn/","pos":"v.","cat":"cet4","meaning":"辞职；顺从","example":"He resigned last month.","exampleZh":"他上个月辞职了。"},
{"word":"resist","ipa":"/rɪˈzɪst/","pos":"v.","cat":"cet4","meaning":"抵抗","example":"Resist the temptation.","exampleZh":"抵制诱惑。"},
{"word":"resolve","ipa":"/rɪˈzɒlv/","pos":"v.","cat":"cet4","meaning":"解决；决心","example":"Resolve the conflict.","exampleZh":"解决冲突。"},
{"word":"respect","ipa":"/rɪˈspekt/","pos":"n./v.","cat":"cet4","meaning":"尊重","example":"Show respect.","exampleZh":"表示尊重。"},
{"word":"respond","ipa":"/rɪˈspɒnd/","pos":"v.","cat":"cet4","meaning":"回应","example":"She responded quickly.","exampleZh":"她很快回应了。"},
{"word":"response","ipa":"/rɪˈspɒns/","pos":"n.","cat":"cet4","meaning":"回应","example":"No response yet.","exampleZh":"还没有回应。"},
{"word":"responsibility","ipa":"/rɪˌspɒnsəˈbɪləti/","pos":"n.","cat":"cet4","meaning":"责任","example":"Take responsibility.","exampleZh":"承担责任。"},
{"word":"restore","ipa":"/rɪˈstɔːr/","pos":"v.","cat":"cet4","meaning":"恢复；修复","example":"Restore the file.","exampleZh":"恢复文件。"},
{"word":"restrict","ipa":"/rɪˈstrɪkt/","pos":"v.","cat":"cet4","meaning":"限制","example":"Restrict access.","exampleZh":"限制访问。"},
{"word":"retain","ipa":"/rɪˈteɪn/","pos":"v.","cat":"cet4","meaning":"保留","example":"Retain the right.","exampleZh":"保留权利。"},
{"word":"retire","ipa":"/rɪˈtaɪər/","pos":"v.","cat":"cet4","meaning":"退休","example":"He retired at 60.","exampleZh":"他60岁退休。"},
{"word":"reveal","ipa":"/rɪˈviːl/","pos":"v.","cat":"cet4","meaning":"揭示；展现","example":"The report revealed the truth.","exampleZh":"报告揭露了真相。"},
{"word":"revenue","ipa":"/ˈrevənjuː/","pos":"n.","cat":"cet4","meaning":"收入；税收","example":"Tax revenue rose.","exampleZh":"税收增加。"},
{"word":"reverse","ipa":"/rɪˈvɜːrs/","pos":"v./adj.","cat":"cet4","meaning":"颠倒；相反的","example":"Reverse the order.","exampleZh":"颠倒顺序。"},
{"word":"revise","ipa":"/rɪˈvaɪz/","pos":"v.","cat":"cet4","meaning":"修订；复习","example":"Revise the draft.","exampleZh":"修改草稿。"},
{"word":"revolution","ipa":"/ˌrevəˈluːʃn/","pos":"n.","cat":"cet4","meaning":"革命","example":"The industrial revolution.","exampleZh":"工业革命。"},
{"word":"reward","ipa":"/rɪˈwɔːrd/","pos":"n./v.","cat":"cet4","meaning":"奖励","example":"Hard work brings reward.","exampleZh":"努力带来回报。"},
{"word":"rid","ipa":"/rɪd/","pos":"v.","cat":"cet4","meaning":"使摆脱","example":"Rid the room of clutter.","exampleZh":"清理房间杂物。"},
{"word":"rigid","ipa":"/ˈrɪdʒɪd/","pos":"adj.","cat":"cet4","meaning":"僵硬的；严格的","example":"A rigid rule.","exampleZh":"死板的规定。"},
{"word":"ripe","ipa":"/raɪp/","pos":"adj.","cat":"cet4","meaning":"成熟的","example":"Ripe fruit.","exampleZh":"成熟的水果。"},
{"word":"rival","ipa":"/ˈraɪvl/","pos":"n./v.","cat":"cet4","meaning":"对手；竞争","example":"A business rival.","exampleZh":"商业对手。"},
{"word":"rob","ipa":"/rɒb/","pos":"v.","cat":"cet4","meaning":"抢劫","example":"He was robbed.","exampleZh":"他遭抢劫了。"},
{"word":"robust","ipa":"/roʊˈbʌst/","pos":"adj.","cat":"cet4","meaning":"健壮的；稳健的","example":"A robust system.","exampleZh":"稳健的系统。"},
{"word":"role","ipa":"/roʊl/","pos":"n.","cat":"cet4","meaning":"角色；作用","example":"Play a key role.","exampleZh":"起关键作用。"},
{"word":"rural","ipa":"/ˈrʊrəl/","pos":"adj.","cat":"cet4","meaning":"农村的","example":"Rural areas.","exampleZh":"农村地区。"},
{"word":"sacrifice","ipa":"/ˈsækrɪfaɪs/","pos":"n./v.","cat":"cet4","meaning":"牺牲","example":"He sacrificed his time.","exampleZh":"他牺牲了时间。"},
{"word":"sample","ipa":"/ˈsæmpl/","pos":"n./v.","cat":"cet4","meaning":"样本；抽样","example":"A blood sample.","exampleZh":"血样。"},
{"word":"sanction","ipa":"/ˈsæŋkʃn/","pos":"n./v.","cat":"cet4","meaning":"制裁；批准","example":"Trade sanctions.","exampleZh":"贸易制裁。"},
{"word":"satisfy","ipa":"/ˈsætɪsfaɪ/","pos":"v.","cat":"cet4","meaning":"满足","example":"The result satisfied him.","exampleZh":"结果令他满意。"},
{"word":"scale","ipa":"/skeɪl/","pos":"n./v.","cat":"cet4","meaning":"规模；比例","example":"Economies of scale.","exampleZh":"规模经济。"},
{"word":"scan","ipa":"/skæn/","pos":"v.","cat":"cet4","meaning":"扫描；浏览","example":"Scan the document.","exampleZh":"扫描文件。"},
{"word":"scatter","ipa":"/ˈskætər/","pos":"v.","cat":"cet4","meaning":"散开；散布","example":"Scatter the seeds.","exampleZh":"撒播种子。"},
{"word":"scene","ipa":"/siːn/","pos":"n.","cat":"cet4","meaning":"场景；景色","example":"A beautiful scene.","exampleZh":"美丽的景色。"},
{"word":"schedule","ipa":"/ˈskedʒuːl/","pos":"n./v.","cat":"cet4","meaning":"日程；安排","example":"Check the schedule.","exampleZh":"查看日程。"},
{"word":"scheme","ipa":"/skiːm/","pos":"n.","cat":"cet4","meaning":"计划； scheme","example":"A training scheme.","exampleZh":"一项培训计划。"},
{"word":"scope","ipa":"/skoʊp/","pos":"n.","cat":"cet4","meaning":"范围","example":"Beyond the scope.","exampleZh":"超出范围。"},
{"word":"score","ipa":"/skɔːr/","pos":"n./v.","cat":"cet4","meaning":"分数；得分","example":"He scored high.","exampleZh":"他得分很高。"},
{"word":"scratch","ipa":"/skrætʃ/","pos":"v./n.","cat":"cet4","meaning":"抓； scratch","example":"Start from scratch.","exampleZh":"从零开始。"},
{"word":"secure","ipa":"/sɪˈkjʊr/","pos":"adj./v.","cat":"cet4","meaning":"安全的；获得","example":"Secure the network.","exampleZh":"保障网络安全。"},
{"word":"segment","ipa":"/ˈseɡmənt/","pos":"n.","cat":"cet4","meaning":"部分；段","example":"A market segment.","exampleZh":"细分市场。"},
{"word":"select","ipa":"/sɪˈlekt/","pos":"v.","cat":"cet4","meaning":"选择","example":"Select an option.","exampleZh":"选一个选项。"},
{"word":"senior","ipa":"/ˈsiːniər/","pos":"adj./n.","cat":"cet4","meaning":"资深的；高年级生","example":"A senior engineer.","exampleZh":"资深工程师。"},
{"word":"sensitive","ipa":"/ˈsensətɪv/","pos":"adj.","cat":"cet4","meaning":"敏感的","example":"Be sensitive to others.","exampleZh":"体谅他人。"},
{"word":"sequence","ipa":"/ˈsiːkwəns/","pos":"n.","cat":"cet4","meaning":"顺序","example":"In sequence.","exampleZh":"按顺序。"},
{"word":"series","ipa":"/ˈsɪriːz/","pos":"n.","cat":"cet4","meaning":"系列","example":"A series of events.","exampleZh":"一系列事件。"},
{"word":"settle","ipa":"/ˈsetl/","pos":"v.","cat":"cet4","meaning":"解决；定居","example":"Settle the dispute.","exampleZh":"解决争端。"},
{"word":"severe","ipa":"/sɪˈvɪr/","pos":"adj.","cat":"cet4","meaning":"严重的；严厉的","example":"A severe storm.","exampleZh":"猛烈的暴风雨。"},
{"word":"sexual","ipa":"/ˈsekʃuəl/","pos":"adj.","cat":"cet4","meaning":"性的","example":"Sexual equality.","exampleZh":"性别平等。"},
{"word":"shadow","ipa":"/ˈʃædoʊ/","pos":"n.","cat":"cet4","meaning":"影子","example":"The tree cast a shadow.","exampleZh":"树投下影子。"},
{"word":"shrink","ipa":"/ʃrɪŋk/","pos":"v.","cat":"cet4","meaning":"收缩；缩小","example":"The shirt shrank.","exampleZh":"衬衫缩水了。"},
{"word":"significant","ipa":"/sɪɡˈnɪfɪkənt/","pos":"adj.","cat":"cet4","meaning":"重要的；显著的","example":"A significant change.","exampleZh":"重大变化。"},
{"word":"similar","ipa":"/ˈsɪmələr/","pos":"adj.","cat":"cet4","meaning":"相似的","example":"A similar case.","exampleZh":"类似案例。"},
{"word":"simulate","ipa":"/ˈsɪmjuleɪt/","pos":"v.","cat":"cet4","meaning":"模拟","example":"Simulate the process.","exampleZh":"模拟过程。"},
{"word":"sincere","ipa":"/sɪnˈsɪr/","pos":"adj.","cat":"cet4","meaning":"真诚的","example":"A sincere apology.","exampleZh":"真诚的道歉。"},
{"word":"sketch","ipa":"/sketʃ/","pos":"n./v.","cat":"cet4","meaning":"草图；速写","example":"Draw a sketch.","exampleZh":"画草图。"},
{"word":"slight","ipa":"/slaɪt/","pos":"adj.","cat":"cet4","meaning":"轻微的","example":"A slight error.","exampleZh":"小错误。"},
{"word":"slope","ipa":"/sloʊp/","pos":"n.","cat":"cet4","meaning":"斜坡","example":"The hill has a slope.","exampleZh":"山坡有斜度。"},
{"word":"smash","ipa":"/smæʃ/","pos":"v.","cat":"cet4","meaning":"打碎；猛撞","example":"He smashed the record.","exampleZh":"他打破了纪录。"},
{"word":"soak","ipa":"/soʊk/","pos":"v.","cat":"cet4","meaning":"浸泡","example":"Soak the beans.","exampleZh":"泡豆子。"},
{"word":"solar","ipa":"/ˈsoʊlər/","pos":"adj.","cat":"cet4","meaning":"太阳的","example":"Solar energy.","exampleZh":"太阳能。"},
{"word":"sole","ipa":"/soʊl/","pos":"adj.","cat":"cet4","meaning":"唯一的","example":"The sole owner.","exampleZh":"唯一所有者。"},
{"word":"solemn","ipa":"/ˈsɒləm/","pos":"adj.","cat":"cet4","meaning":"庄严的","example":"A solemn promise.","exampleZh":"庄严的承诺。"},
{"word":"solid","ipa":"/ˈsɒlɪd/","pos":"adj./n.","cat":"cet4","meaning":"固体的；可靠的","example":"A solid plan.","exampleZh":"稳妥的计划。"},
{"word":"soluble","ipa":"/ˈsɒljəbl/","pos":"adj.","cat":"cet4","meaning":"可溶的","example":"Salt is soluble.","exampleZh":"盐可溶。"},
{"word":"solve","ipa":"/sɒlv/","pos":"v.","cat":"cet4","meaning":"解决","example":"Solve the puzzle.","exampleZh":"解谜。"},
{"word":"somewhat","ipa":"/ˈsʌmwʌt/","pos":"adv.","cat":"cet4","meaning":"有点","example":"I am somewhat tired.","exampleZh":"我有点累。"},
{"word":"sophisticated","ipa":"/səˈfɪstɪkeɪtɪd/","pos":"adj.","cat":"cet4","meaning":"精密的；老练的","example":"Sophisticated software.","exampleZh":"精密的软件。"},
{"word":"source","ipa":"/sɔːrs/","pos":"n.","cat":"cet4","meaning":"来源","example":"The source of the river.","exampleZh":"河的源头。"}
];
