// 离线词库分片 2/5（由 split_offline_dict.js 生成，勿手改）
var OFFLINE_EXTRA_2 = [
{"word":"corresponding","ipa":"/ˌkɔːrəˈspɒndɪŋ/","pos":"adj.","cat":"cet4","meaning":"相应的；对应的","example":"The pay matches the corresponding role.","exampleZh":"薪酬与相应岗位匹配。"},
{"word":"council","ipa":"/ˈkaʊnsl/","pos":"n.","cat":"cet4","meaning":"委员会；理事会","example":"The city council met.","exampleZh":"市议会开会了。"},
{"word":"create","ipa":"/kriˈeɪt/","pos":"v.","cat":"cet4","meaning":"创造","example":"They created a new app.","exampleZh":"他们开发了一款新应用。"},
{"word":"creature","ipa":"/ˈkriːtʃər/","pos":"n.","cat":"cet4","meaning":"生物； creature","example":"A strange creature appeared.","exampleZh":"一个奇怪的生物出现了。"},
{"word":"credit","ipa":"/ˈkredɪt/","pos":"n./v.","cat":"cet4","meaning":"信用；学分；归功于","example":"She got course credit.","exampleZh":"她拿到了课程学分。"},
{"word":"crisis","ipa":"/ˈkraɪsɪs/","pos":"n.","cat":"cet4","meaning":"危机","example":"The firm faced a crisis.","exampleZh":"公司面临危机。"},
{"word":"critic","ipa":"/ˈkrɪtɪk/","pos":"n.","cat":"cet4","meaning":"批评家；评论员","example":"The critic praised the film.","exampleZh":"评论家称赞了这部电影。"},
{"word":"critical","ipa":"/ˈkrɪtɪkl/","pos":"adj.","cat":"cet4","meaning":"关键的；挑剔的","example":"Timing is critical.","exampleZh":"时机很关键。"},
{"word":"criticism","ipa":"/ˈkrɪtɪsɪzəm/","pos":"n.","cat":"cet4","meaning":"批评","example":"He accepted the criticism.","exampleZh":"他接受了批评。"},
{"word":"culture","ipa":"/ˈkʌltʃər/","pos":"n.","cat":"cet4","meaning":"文化","example":"Food reflects culture.","exampleZh":"食物反映文化。"},
{"word":"cure","ipa":"/kjʊr/","pos":"v./n.","cat":"cet4","meaning":"治愈；疗法","example":"Scientists seek a cure.","exampleZh":"科学家在寻找疗法。"},
{"word":"curious","ipa":"/ˈkjʊriəs/","pos":"adj.","cat":"cet4","meaning":"好奇的","example":"The child is curious.","exampleZh":"这孩子很好奇。"},
{"word":"current","ipa":"/ˈkʌrənt/","pos":"adj./n.","cat":"cet4","meaning":"当前的；电流","example":"The current policy changed.","exampleZh":"现行政策变了。"},
{"word":"custom","ipa":"/ˈkʌstəm/","pos":"n.","cat":"cet4","meaning":"习俗；习惯","example":"It is a local custom.","exampleZh":"这是当地习俗。"},
{"word":"decline","ipa":"/dɪˈklaɪn/","pos":"v./n.","cat":"cet4","meaning":"下降；拒绝","example":"He declined the offer.","exampleZh":"他拒绝了提议。"},
{"word":"dedicate","ipa":"/ˈdedɪkeɪt/","pos":"v.","cat":"cet4","meaning":"致力于","example":"She dedicated her life to art.","exampleZh":"她毕生献身艺术。"},
{"word":"defend","ipa":"/dɪˈfend/","pos":"v.","cat":"cet4","meaning":"防御；辩护","example":"They defended the city.","exampleZh":"他们保卫了城市。"},
{"word":"define","ipa":"/dɪˈfaɪn/","pos":"v.","cat":"cet4","meaning":"定义","example":"Define the term clearly.","exampleZh":"把术语定义清楚。"},
{"word":"deliver","ipa":"/dɪˈlɪvər/","pos":"v.","cat":"cet4","meaning":"递送；发表","example":"The mail was delivered.","exampleZh":"邮件已送达。"},
{"word":"demand","ipa":"/dɪˈmænd/","pos":"n./v.","cat":"cet4","meaning":"需求；要求","example":"Supply meets demand.","exampleZh":"供需平衡。"},
{"word":"demonstrate","ipa":"/ˈdemənstreɪt/","pos":"v.","cat":"cet4","meaning":"证明；演示","example":"He demonstrated the method.","exampleZh":"他演示了方法。"},
{"word":"deny","ipa":"/dɪˈnaɪ/","pos":"v.","cat":"cet4","meaning":"否认；拒绝给予","example":"She denied the rumor.","exampleZh":"她否认了谣言。"},
{"word":"depend","ipa":"/dɪˈpend/","pos":"v.","cat":"cet4","meaning":"依赖","example":"It depends on the weather.","exampleZh":"这取决于天气。"},
{"word":"depress","ipa":"/dɪˈpres/","pos":"v.","cat":"cet4","meaning":"使沮丧；压下","example":"The news depressed him.","exampleZh":"这消息让他沮丧。"},
{"word":"derive","ipa":"/dɪˈraɪv/","pos":"v.","cat":"cet4","meaning":"源于；得到","example":"We derive energy from food.","exampleZh":"我们从食物获取能量。"},
{"word":"descend","ipa":"/dɪˈsend/","pos":"v.","cat":"cet4","meaning":"下降；下来","example":"The sun descended.","exampleZh":"太阳落下了。"},
{"word":"deserve","ipa":"/dɪˈzɜːrv/","pos":"v.","cat":"cet4","meaning":"应得","example":"He deserves praise.","exampleZh":"他值得表扬。"},
{"word":"design","ipa":"/dɪˈzaɪn/","pos":"v./n.","cat":"cet4","meaning":"设计","example":"She designed the logo.","exampleZh":"她设计了徽标。"},
{"word":"desire","ipa":"/dɪˈzaɪər/","pos":"n./v.","cat":"cet4","meaning":"渴望","example":"He desires success.","exampleZh":"他渴望成功。"},
{"word":"despair","ipa":"/dɪˈsper/","pos":"n./v.","cat":"cet4","meaning":"绝望","example":"She fell into despair.","exampleZh":"她陷入绝望。"},
{"word":"despite","ipa":"/dɪˈspaɪt/","pos":"prep.","cat":"cet4","meaning":"尽管","example":"Despite the rain, we went.","exampleZh":"尽管下雨我们还是去了。"},
{"word":"destiny","ipa":"/ˈdestəni/","pos":"n.","cat":"cet4","meaning":"命运","example":"He believed in his destiny.","exampleZh":"他相信自己的命运。"},
{"word":"destroy","ipa":"/dɪˈstrɔɪ/","pos":"v.","cat":"cet4","meaning":"摧毁","example":"The fire destroyed the house.","exampleZh":"大火烧毁了房子。"},
{"word":"detail","ipa":"/ˈdiːteɪl/","pos":"n.","cat":"cet4","meaning":"细节","example":"Notice every detail.","exampleZh":"注意每个细节。"},
{"word":"detect","ipa":"/dɪˈtekt/","pos":"v.","cat":"cet4","meaning":"察觉；检测","example":"The sensor detected motion.","exampleZh":"传感器检测到了移动。"},
{"word":"develop","ipa":"/dɪˈveləp/","pos":"v.","cat":"cet4","meaning":"发展；开发","example":"They developed a new drug.","exampleZh":"他们研发了一种新药。"},
{"word":"devote","ipa":"/dɪˈvoʊt/","pos":"v.","cat":"cet4","meaning":"奉献；致力于","example":"She devoted time to reading.","exampleZh":"她把时间用于阅读。"},
{"word":"differ","ipa":"/ˈdɪfər/","pos":"v.","cat":"cet4","meaning":"不同；有分歧","example":"Opinions differ.","exampleZh":"意见不一。"},
{"word":"digest","ipa":"/daɪˈdʒest/","pos":"v.","cat":"cet4","meaning":"消化；领会","example":"It takes time to digest.","exampleZh":"消化需要时间。"},
{"word":"discipline","ipa":"/ˈdɪsəplɪn/","pos":"n./v.","cat":"cet4","meaning":"纪律；训练","example":"Self-discipline is key.","exampleZh":"自律是关键。"},
{"word":"discover","ipa":"/dɪˈskʌvər/","pos":"v.","cat":"cet4","meaning":"发现","example":"They discovered a new star.","exampleZh":"他们发现了一颗新星。"},
{"word":"discriminate","ipa":"/dɪˈskrɪmɪneɪt/","pos":"v.","cat":"cet4","meaning":"区分；歧视","example":"Do not discriminate.","exampleZh":"不要歧视。"},
{"word":"dismiss","ipa":"/dɪsˈmɪs/","pos":"v.","cat":"cet4","meaning":"解散；解雇；不予考虑","example":"He was dismissed.","exampleZh":"他被解雇了。"},
{"word":"disorder","ipa":"/dɪsˈɔːrdər/","pos":"n.","cat":"cet4","meaning":"混乱；失调","example":"The room was in disorder.","exampleZh":"房间一片混乱。"},
{"word":"display","ipa":"/dɪˈspleɪ/","pos":"v./n.","cat":"cet4","meaning":"展示；显示","example":"The shop displayed new goods.","exampleZh":"商店展示了新商品。"},
{"word":"dispose","ipa":"/dɪˈspoʊz/","pos":"v.","cat":"cet4","meaning":"处理；布置","example":"Dispose of waste properly.","exampleZh":"妥善处理废物。"},
{"word":"distance","ipa":"/ˈdɪstəns/","pos":"n.","cat":"cet4","meaning":"距离","example":"The distance is ten km.","exampleZh":"距离是十公里。"},
{"word":"distinct","ipa":"/dɪˈstɪŋkt/","pos":"adj.","cat":"cet4","meaning":"清晰的；不同的","example":"They have distinct accents.","exampleZh":"他们口音明显不同。"},
{"word":"distribute","ipa":"/dɪˈstrɪbjuːt/","pos":"v.","cat":"cet4","meaning":"分配；分发","example":"Food was distributed to victims.","exampleZh":"食物分发给了灾民。"},
{"word":"diverse","ipa":"/daɪˈvɜːrs/","pos":"adj.","cat":"cet4","meaning":"多样的","example":"The city is culturally diverse.","exampleZh":"这座城市文化多元。"},
{"word":"document","ipa":"/ˈdɒkjumənt/","pos":"n.","cat":"cet4","meaning":"文件","example":"Sign the document.","exampleZh":"在文件上签字。"},
{"word":"domestic","ipa":"/dəˈmestɪk/","pos":"adj.","cat":"cet4","meaning":"国内的；家庭的","example":"Domestic sales grew.","exampleZh":"国内销售增长。"},
{"word":"dominate","ipa":"/ˈdɒmɪneɪt/","pos":"v.","cat":"cet4","meaning":"主导；支配","example":"One team dominated.","exampleZh":"一支队伍占据了主导。"},
{"word":"doubt","ipa":"/daʊt/","pos":"n./v.","cat":"cet4","meaning":"怀疑","example":"I doubt his story.","exampleZh":"我怀疑他的说法。"},
{"word":"dramatic","ipa":"/drəˈmætɪk/","pos":"adj.","cat":"cet4","meaning":"戏剧性的；显著的","example":"There was a dramatic change.","exampleZh":"发生了显著变化。"},
{"word":"duration","ipa":"/djuˈreɪʃn/","pos":"n.","cat":"cet4","meaning":"持续时间","example":"The duration is two hours.","exampleZh":"时长为两小时。"},
{"word":"eager","ipa":"/ˈiːɡər/","pos":"adj.","cat":"cet4","meaning":"渴望的","example":"He is eager to learn.","exampleZh":"他渴望学习。"},
{"word":"earn","ipa":"/ɜːrn/","pos":"v.","cat":"cet4","meaning":"赚得；赢得","example":"She earned a bonus.","exampleZh":"她拿到了奖金。"},
{"word":"economic","ipa":"/ˌiːkəˈnɒmɪk/","pos":"adj.","cat":"cet4","meaning":"经济的","example":"The region is economic.","exampleZh":"该地区经济发达。"},
{"word":"economy","ipa":"/ɪˈkɒnəmi/","pos":"n.","cat":"cet4","meaning":"经济","example":"The economy recovered.","exampleZh":"经济复苏了。"},
{"word":"educate","ipa":"/ˈedʒukeɪt/","pos":"v.","cat":"cet4","meaning":"教育","example":"Schools educate children.","exampleZh":"学校教育孩子。"},
{"word":"effective","ipa":"/ɪˈfektɪv/","pos":"adj.","cat":"cet4","meaning":"有效的","example":"The method is effective.","exampleZh":"这个方法有效。"},
{"word":"efficient","ipa":"/ɪˈfɪʃnt/","pos":"adj.","cat":"cet4","meaning":"高效的","example":"We need an efficient system.","exampleZh":"我们需要高效的系统。"},
{"word":"elaborate","ipa":"/ɪˈlæbərət/","pos":"adj./v.","cat":"cet4","meaning":"详尽的；详述","example":"Please elaborate your point.","exampleZh":"请详述你的观点。"},
{"word":"elect","ipa":"/ɪˈlekt/","pos":"v.","cat":"cet4","meaning":"选举；选择","example":"They elected a leader.","exampleZh":"他们选出了领导。"},
{"word":"element","ipa":"/ˈelɪmənt/","pos":"n.","cat":"cet4","meaning":"元素；要素","example":"Trust is a key element.","exampleZh":"信任是关键要素。"},
{"word":"embrace","ipa":"/ɪmˈbreɪs/","pos":"v.","cat":"cet4","meaning":"拥抱；接纳","example":"They embraced the change.","exampleZh":"他们接纳了变化。"},
{"word":"emerge","ipa":"/ɪˈmɜːrdʒ/","pos":"v.","cat":"cet4","meaning":"出现；浮现","example":"A new trend emerged.","exampleZh":"一个新趋势出现了。"},
{"word":"emotion","ipa":"/ɪˈmoʊʃn/","pos":"n.","cat":"cet4","meaning":"情感","example":"Music conveys emotion.","exampleZh":"音乐传递情感。"},
{"word":"emphasis","ipa":"/ˈemfəsɪs/","pos":"n.","cat":"cet4","meaning":"强调","example":"He placed emphasis on safety.","exampleZh":"他强调了安全。"},
{"word":"employ","ipa":"/ɪmˈplɔɪ/","pos":"v.","cat":"cet4","meaning":"雇佣；使用","example":"The firm employs 200 staff.","exampleZh":"公司雇佣了200名员工。"},
{"word":"enable","ipa":"/ɪˈneɪbl/","pos":"v.","cat":"cet4","meaning":"使能够","example":"The tool enables faster work.","exampleZh":"这工具让工作更快。"},
{"word":"encounter","ipa":"/ɪnˈkaʊntər/","pos":"v./n.","cat":"cet4","meaning":"遭遇；邂逅","example":"We encountered a problem.","exampleZh":"我们遇到了问题。"},
{"word":"encourage","ipa":"/ɪnˈkʌrɪdʒ/","pos":"v.","cat":"cet4","meaning":"鼓励","example":"She encouraged my dream.","exampleZh":"她鼓励我的梦想。"},
{"word":"endure","ipa":"/ɪnˈdʊr/","pos":"v.","cat":"cet4","meaning":"忍受；持续","example":"They endured hardship.","exampleZh":"他们忍受了艰难。"},
{"word":"enforce","ipa":"/ɪnˈfɔːrs/","pos":"v.","cat":"cet4","meaning":"执行；强制","example":"The law is enforced.","exampleZh":"法律得到执行。"},
{"word":"engage","ipa":"/ɪnˈɡeɪdʒ/","pos":"v.","cat":"cet4","meaning":"从事；吸引；订婚","example":"Engage the audience.","exampleZh":"吸引观众。"},
{"word":"enhance","ipa":"/ɪnˈhæns/","pos":"v.","cat":"cet4","meaning":"增强","example":"Training enhances skill.","exampleZh":"训练提升技能。"},
{"word":"enormous","ipa":"/ɪˈnɔːrməs/","pos":"adj.","cat":"cet4","meaning":"巨大的","example":"An enormous crowd gathered.","exampleZh":"聚集了巨大的人群。"},
{"word":"ensure","ipa":"/ɪnˈʃʊr/","pos":"v.","cat":"cet4","meaning":"确保","example":"Ensure the door is locked.","exampleZh":"确保门锁好。"},
{"word":"entire","ipa":"/ɪnˈtaɪər/","pos":"adj.","cat":"cet4","meaning":"全部的","example":"The entire team agreed.","exampleZh":"全体团队都同意。"},
{"word":"entitle","ipa":"/ɪnˈtaɪtl/","pos":"v.","cat":"cet4","meaning":"使有权利","example":"The ticket entitles you to enter.","exampleZh":"这张票让你有权入场。"},
{"word":"environment","ipa":"/ɪnˈvaɪrənmənt/","pos":"n.","cat":"cet4","meaning":"环境","example":"Protect the environment.","exampleZh":"保护环境。"},
{"word":"equality","ipa":"/iˈkwɒləti/","pos":"n.","cat":"cet4","meaning":"平等","example":"They fought for equality.","exampleZh":"他们为平等而战。"},
{"word":"equip","ipa":"/ɪˈkwɪp/","pos":"v.","cat":"cet4","meaning":"装备；配备","example":"The lab is well equipped.","exampleZh":"实验室设备齐全。"},
{"word":"essential","ipa":"/ɪˈsenʃl/","pos":"adj.","cat":"cet4","meaning":"必要的；本质的","example":"Water is essential.","exampleZh":"水是必要的。"},
{"word":"establish","ipa":"/ɪˈstæblɪʃ/","pos":"v.","cat":"cet4","meaning":"建立；确立","example":"They established a company.","exampleZh":"他们创立了一家公司。"},
{"word":"estimate","ipa":"/ˈestɪmeɪt/","pos":"v./n.","cat":"cet4","meaning":"估计","example":"We estimate the cost.","exampleZh":"我们估算了成本。"},
{"word":"evaluate","ipa":"/ɪˈvæljueɪt/","pos":"v.","cat":"cet4","meaning":"评估","example":"Evaluate the proposal.","exampleZh":"评估这个提案。"},
{"word":"evidence","ipa":"/ˈevɪdəns/","pos":"n.","cat":"cet4","meaning":"证据","example":"There is no evidence.","exampleZh":"没有证据。"},
{"word":"evident","ipa":"/ˈevɪdənt/","pos":"adj.","cat":"cet4","meaning":"明显的","example":"His joy was evident.","exampleZh":"他的喜悦显而易见。"},
{"word":"evolve","ipa":"/ɪˈvɒlv/","pos":"v.","cat":"cet4","meaning":"进化；发展","example":"Language evolves.","exampleZh":"语言在演变。"},
{"word":"exaggerate","ipa":"/ɪɡˈzædʒəreɪt/","pos":"v.","cat":"cet4","meaning":"夸大","example":"Do not exaggerate.","exampleZh":"不要夸大。"},
{"word":"exceed","ipa":"/ɪkˈsiːd/","pos":"v.","cat":"cet4","meaning":"超过","example":"Costs exceeded the budget.","exampleZh":"成本超出预算。"},
{"word":"exception","ipa":"/ɪkˈsepʃn/","pos":"n.","cat":"cet4","meaning":"例外","example":"There is no exception.","exampleZh":"没有例外。"},
{"word":"excess","ipa":"/ɪkˈses/","pos":"n./adj.","cat":"cet4","meaning":"过量；过度的","example":"Avoid excess sugar.","exampleZh":"少吃糖。"},
{"word":"exchange","ipa":"/ɪksˈtʃeɪndʒ/","pos":"v./n.","cat":"cet4","meaning":"交换","example":"We exchanged ideas.","exampleZh":"我们交流了想法。"},
{"word":"exclude","ipa":"/ɪkˈskluːd/","pos":"v.","cat":"cet4","meaning":"排除；不包括","example":"Children are excluded.","exampleZh":"儿童不包括在内。"},
{"word":"exhibit","ipa":"/ɪɡˈzɪbɪt/","pos":"v./n.","cat":"cet4","meaning":"展示；展品","example":"The museum exhibits art.","exampleZh":"博物馆展出艺术品。"},
{"word":"exist","ipa":"/ɪɡˈzɪst/","pos":"v.","cat":"cet4","meaning":"存在","example":"No such file exists.","exampleZh":"不存在这样的文件。"},
{"word":"expand","ipa":"/ɪkˈspænd/","pos":"v.","cat":"cet4","meaning":"扩张；扩展","example":"The business expanded.","exampleZh":"业务扩张了。"},
{"word":"expend","ipa":"/ɪkˈspend/","pos":"v.","cat":"cet4","meaning":"花费；消耗","example":"They expended much effort.","exampleZh":"他们付出了很多努力。"},
{"word":"expense","ipa":"/ɪkˈspens/","pos":"n.","cat":"cet4","meaning":"花费；开支","example":"Travel is a big expense.","exampleZh":"旅行是一笔大开销。"},
{"word":"explain","ipa":"/ɪkˈspleɪn/","pos":"v.","cat":"cet4","meaning":"解释","example":"Explain your reasoning.","exampleZh":"解释你的推理。"},
{"word":"explore","ipa":"/ɪkˈsplɔːr/","pos":"v.","cat":"cet4","meaning":"探索","example":"Explore the options.","exampleZh":"探索各种选项。"},
{"word":"export","ipa":"/ɪkˈspɔːrt/","pos":"v./n.","cat":"cet4","meaning":"出口","example":"The country exports rice.","exampleZh":"该国出口大米。"},
{"word":"expose","ipa":"/ɪkˈspoʊz/","pos":"v.","cat":"cet4","meaning":"暴露；揭露","example":"The roof was exposed.","exampleZh":"屋顶暴露在外。"},
{"word":"extend","ipa":"/ɪkˈstend/","pos":"v.","cat":"cet4","meaning":"延伸；延长","example":"Extend the deadline.","exampleZh":"延长截止日期。"},
{"word":"external","ipa":"/ɪkˈstɜːrnl/","pos":"adj.","cat":"cet4","meaning":"外部的","example":"External factors matter.","exampleZh":"外部因素很重要。"},
{"word":"facilitate","ipa":"/fəˈsɪlɪteɪt/","pos":"v.","cat":"cet4","meaning":"促进；使便利","example":"The app facilitates study.","exampleZh":"这个应用方便了学习。"},
{"word":"factor","ipa":"/ˈfæktər/","pos":"n.","cat":"cet4","meaning":"因素","example":"Price is a key factor.","exampleZh":"价格是关键因素。"},
{"word":"fade","ipa":"/feɪd/","pos":"v.","cat":"cet4","meaning":"褪色；逐渐消失","example":"The light faded.","exampleZh":"灯光暗淡下去。"},
{"word":"failure","ipa":"/ˈfeɪljər/","pos":"n.","cat":"cet4","meaning":"失败","example":"Failure taught him.","exampleZh":"失败教育了他。"},
{"word":"fancy","ipa":"/ˈfænsi/","pos":"adj./v.","cat":"cet4","meaning":"花哨的；喜欢","example":"She fancies the dress.","exampleZh":"她喜欢那条裙子。"},
{"word":"fatal","ipa":"/ˈfeɪtl/","pos":"adj.","cat":"cet4","meaning":"致命的","example":"The accident was fatal.","exampleZh":"事故是致命的。"},
{"word":"fault","ipa":"/fɔːlt/","pos":"n.","cat":"cet4","meaning":"过错；故障","example":"It is not my fault.","exampleZh":"这不是我的错。"},
{"word":"favor","ipa":"/ˈfeɪvər/","pos":"n./v.","cat":"cet4","meaning":"偏爱；帮忙","example":"Could you do me a favor?","exampleZh":"能帮我个忙吗？"},
{"word":"feature","ipa":"/ˈfiːtʃər/","pos":"n./v.","cat":"cet4","meaning":"特征；以…为特色","example":"The phone features a big screen.","exampleZh":"这款手机有大屏特色。"},
{"word":"federal","ipa":"/ˈfedərəl/","pos":"adj.","cat":"cet4","meaning":"联邦的","example":"The federal government acted.","exampleZh":"联邦政府采取了行动。"},
{"word":"fee","ipa":"/fiː/","pos":"n.","cat":"cet4","meaning":"费用","example":"The entry fee is low.","exampleZh":"入场费很低。"},
{"word":"file","ipa":"/faɪl/","pos":"n./v.","cat":"cet4","meaning":"文件；归档","example":"File the report.","exampleZh":"把报告归档。"},
{"word":"finance","ipa":"/faɪˈnæns/","pos":"n./v.","cat":"cet4","meaning":"金融；资助","example":"He studies finance.","exampleZh":"他学金融。"},
{"word":"flexible","ipa":"/ˈfleksəbl/","pos":"adj.","cat":"cet4","meaning":"灵活的","example":"We need a flexible plan.","exampleZh":"我们需要灵活的计划。"},
{"word":"fluent","ipa":"/ˈfluːənt/","pos":"adj.","cat":"cet4","meaning":"流利的","example":"She is fluent in English.","exampleZh":"她英语流利。"},
{"word":"focus","ipa":"/ˈfoʊkəs/","pos":"n./v.","cat":"cet4","meaning":"焦点；集中","example":"Focus on the task.","exampleZh":"专注于任务。"},
{"word":"forbid","ipa":"/fərˈbɪd/","pos":"v.","cat":"cet4","meaning":"禁止","example":"Smoking is forbidden.","exampleZh":"禁止吸烟。"},
{"word":"force","ipa":"/fɔːrs/","pos":"n./v.","cat":"cet4","meaning":"力量；强迫","example":"They forced the door.","exampleZh":"他们强行打开了门。"},
{"word":"forecast","ipa":"/ˈfɔːrkæst/","pos":"n./v.","cat":"cet4","meaning":"预测","example":"The forecast was wrong.","exampleZh":"预测错了。"},
{"word":"format","ipa":"/ˈfɔːrmæt/","pos":"n./v.","cat":"cet4","meaning":"格式；格式化","example":"Change the file format.","exampleZh":"更改文件格式。"},
{"word":"former","ipa":"/ˈfɔːrmər/","pos":"adj.","cat":"cet4","meaning":"以前的；前者的","example":"The former boss left.","exampleZh":"前任老板离开了。"},
{"word":"forth","ipa":"/fɔːrθ/","pos":"adv.","cat":"cet4","meaning":"向前；向外","example":"He went forth bravely.","exampleZh":"他勇敢地向前走。"},
{"word":"foundation","ipa":"/faʊnˈdeɪʃn/","pos":"n.","cat":"cet4","meaning":"基础；基金会","example":"Trust is the foundation.","exampleZh":"信任是基础。"},
{"word":"fragment","ipa":"/ˈfræɡmənt/","pos":"n.","cat":"cet4","meaning":"碎片","example":"Only a fragment remained.","exampleZh":"只留下碎片。"},
{"word":"frequent","ipa":"/ˈfriːkwənt/","pos":"adj.","cat":"cet4","meaning":"频繁的","example":"He is a frequent visitor.","exampleZh":"他是常客。"},
{"word":"frown","ipa":"/fraʊn/","pos":"v.","cat":"cet4","meaning":"皱眉","example":"She frowned at the news.","exampleZh":"她听到消息皱了眉。"},
{"word":"function","ipa":"/ˈfʌŋkʃn/","pos":"n./v.","cat":"cet4","meaning":"功能；运行","example":"The device functions well.","exampleZh":"设备运行良好。"},
{"word":"fund","ipa":"/fʌnd/","pos":"n./v.","cat":"cet4","meaning":"资金；资助","example":"They funded the project.","exampleZh":"他们资助了这个项目。"},
{"word":"fundamental","ipa":"/ˌfʌndəˈmentl/","pos":"adj.","cat":"cet4","meaning":"基本的","example":"These are fundamental rights.","exampleZh":"这些是基本权利。"},
{"word":"furthermore","ipa":"/ˌfɜːðərˈmɔːr/","pos":"adv.","cat":"cet4","meaning":"此外","example":"Furthermore, it is cheap.","exampleZh":"此外，它很便宜。"},
{"word":"gap","ipa":"/ɡæp/","pos":"n.","cat":"cet4","meaning":"缺口；差距","example":"There is a gap in service.","exampleZh":"服务存在缺口。"},
{"word":"generate","ipa":"/ˈdʒenəreɪt/","pos":"v.","cat":"cet4","meaning":"产生；生成","example":"The plant generates power.","exampleZh":"电厂发电。"},
{"word":"generous","ipa":"/ˈdʒenərəs/","pos":"adj.","cat":"cet4","meaning":"慷慨的","example":"He is generous with time.","exampleZh":"他舍得花时间。"},
{"word":"genuine","ipa":"/ˈdʒenjʊɪn/","pos":"adj.","cat":"cet4","meaning":"真正的；真诚的","example":"She showed genuine concern.","exampleZh":"她表现出真诚的关心。"},
{"word":"global","ipa":"/ˈɡloʊbl/","pos":"adj.","cat":"cet4","meaning":"全球的","example":"Global warming is serious.","exampleZh":"全球变暖很严重。"},
{"word":"goal","ipa":"/ɡoʊl/","pos":"n.","cat":"cet4","meaning":"目标","example":"Set a clear goal.","exampleZh":"设定明确目标。"},
{"word":"graduate","ipa":"/ˈɡrædʒueɪt/","pos":"v./n.","cat":"cet4","meaning":"毕业；毕业生","example":"She graduated last year.","exampleZh":"她去年毕业。"},
{"word":"grant","ipa":"/ɡrænt/","pos":"v./n.","cat":"cet4","meaning":"授予；拨款","example":"He was granted a visa.","exampleZh":"他拿到了签证。"},
{"word":"grasp","ipa":"/ɡræsp/","pos":"v./n.","cat":"cet4","meaning":"抓住；理解","example":"Grasp the main idea.","exampleZh":"抓住要点。"},
{"word":"grateful","ipa":"/ˈɡreɪtfl/","pos":"adj.","cat":"cet4","meaning":"感激的","example":"I am grateful to you.","exampleZh":"我很感激你。"},
{"word":"guarantee","ipa":"/ˌɡærənˈtiː/","pos":"v./n.","cat":"cet4","meaning":"保证","example":"We guarantee quality.","exampleZh":"我们保证质量。"},
{"word":"guidance","ipa":"/ˈɡaɪdns/","pos":"n.","cat":"cet4","meaning":"指导","example":"He gave me guidance.","exampleZh":"他给了我指导。"},
{"word":"handle","ipa":"/ˈhændl/","pos":"v./n.","cat":"cet4","meaning":"处理；把手","example":"Handle it with care.","exampleZh":"小心处理。"},
{"word":"hardship","ipa":"/ˈhɑːrdʃɪp/","pos":"n.","cat":"cet4","meaning":"艰难；困苦","example":"They overcame hardship.","exampleZh":"他们克服了困苦。"},
{"word":"harmony","ipa":"/ˈhɑːrməni/","pos":"n.","cat":"cet4","meaning":"和谐","example":"Live in harmony.","exampleZh":"和谐共处。"},
{"word":"harsh","ipa":"/hɑːrʃ/","pos":"adj.","cat":"cet4","meaning":"严酷的；刺耳的","example":"The climate is harsh.","exampleZh":"气候严酷。"},
{"word":"highlight","ipa":"/ˈhaɪlaɪt/","pos":"v./n.","cat":"cet4","meaning":"突出；亮点","example":"The report highlights risks.","exampleZh":"报告突出了风险。"},
{"word":"hint","ipa":"/hɪnt/","pos":"n./v.","cat":"cet4","meaning":"暗示；提示","example":"She gave a hint.","exampleZh":"她给了提示。"},
{"word":"host","ipa":"/hoʊst/","pos":"n./v.","cat":"cet4","meaning":"主人；主持","example":"He hosted the event.","exampleZh":"他主持了活动。"},
{"word":"household","ipa":"/ˈhaʊshoʊld/","pos":"n./adj.","cat":"cet4","meaning":"家庭；家用的","example":"Household income rose.","exampleZh":"家庭收入增加。"},
{"word":"humble","ipa":"/ˈhʌmbl/","pos":"adj.","cat":"cet4","meaning":"谦逊的；卑微的","example":"He is humble despite fame.","exampleZh":"他虽有名却很谦逊。"},
{"word":"humor","ipa":"/ˈhjuːmər/","pos":"n.","cat":"cet4","meaning":"幽默","example":"He has a good sense of humor.","exampleZh":"他很有幽默感。"},
{"word":"identify","ipa":"/aɪˈdentɪfaɪ/","pos":"v.","cat":"cet4","meaning":"识别；确认","example":"Identify the problem.","exampleZh":"找出问题。"},
{"word":"ignore","ipa":"/ɪɡˈnɔːr/","pos":"v.","cat":"cet4","meaning":"忽视","example":"Do not ignore the warning.","exampleZh":"不要忽视警告。"},
{"word":"illusion","ipa":"/ɪˈluːʒn/","pos":"n.","cat":"cet4","meaning":"错觉；幻觉","example":"It was an optical illusion.","exampleZh":"那是视觉错觉。"},
{"word":"illustrate","ipa":"/ˈɪləstreɪt/","pos":"v.","cat":"cet4","meaning":"说明；图解","example":"The chart illustrates the trend.","exampleZh":"图表说明了趋势。"},
{"word":"image","ipa":"/ˈɪmɪdʒ/","pos":"n.","cat":"cet4","meaning":"形象；图像","example":"The brand image improved.","exampleZh":"品牌形象改善了。"},
{"word":"immense","ipa":"/ɪˈmens/","pos":"adj.","cat":"cet4","meaning":"巨大的","example":"The task is immense.","exampleZh":"任务巨大。"},
{"word":"impact","ipa":"/ˈɪmpækt/","pos":"n./v.","cat":"cet4","meaning":"影响","example":"The policy had impact.","exampleZh":"政策产生了影响。"},
{"word":"impatient","ipa":"/ɪmˈpeɪʃnt/","pos":"adj.","cat":"cet4","meaning":"不耐烦的","example":"He grew impatient.","exampleZh":"他变得不耐烦。"},
{"word":"implement","ipa":"/ˈɪmplɪment/","pos":"v.","cat":"cet4","meaning":"实施","example":"We implemented the plan.","exampleZh":"我们实施了计划。"},
{"word":"implicate","ipa":"/ˈɪmplɪkeɪt/","pos":"v.","cat":"cet4","meaning":"暗示；牵连","example":"The report implicates several.","exampleZh":"报告牵连到数人。"},
{"word":"import","ipa":"/ɪmˈpɔːrt/","pos":"v./n.","cat":"cet4","meaning":"进口；重要性","example":"The country imports oil.","exampleZh":"该国进口石油。"},
{"word":"impose","ipa":"/ɪmˈpoʊz/","pos":"v.","cat":"cet4","meaning":"强加；征税","example":"They imposed a tax.","exampleZh":"他们征了税。"},
{"word":"impress","ipa":"/ɪmˈpres/","pos":"v.","cat":"cet4","meaning":"给…留下印象","example":"His speech impressed us.","exampleZh":"他的演讲打动了我们。"},
{"word":"improve","ipa":"/ɪmˈpruːv/","pos":"v.","cat":"cet4","meaning":"改善","example":"We improved the design.","exampleZh":"我们改进了设计。"},
{"word":"include","ipa":"/ɪnˈkluːd/","pos":"v.","cat":"cet4","meaning":"包括","example":"The fee includes tax.","exampleZh":"费用含税。"},
{"word":"income","ipa":"/ˈɪnkʌm/","pos":"n.","cat":"cet4","meaning":"收入","example":"Her income increased.","exampleZh":"她的收入增加了。"}
];
